### ISSUE TITLE
UA Circle of Spores (Archetype)

### ISSUE THREAD

**Issue by swdriessen** [aurorabuilder/elements#1]
The circle of spores druidic circle from this [Unearthed Arcana](http://dnd.wizards.com/articles/unearthed-arcana/three-subclasses) article.

[unearthed-arcana/2018/20180108.xml](https://github.com/aurorabuilder/elements/blob/master/unearthed-arcana/2018/20180108.xml)

**Comment by chrisjfoss** [comment]
I'll work on this.
