### ISSUE TITLE
Summery --> Summary (dev mode)

### ISSUE THREAD

**Issue by challenger-of-games** [aurorabuilder/elements#10]
I was surprised to find out that they're both words, but I believe the one that's intended is "summary".

![not-summary](https://user-images.githubusercontent.com/8908585/40283324-679f72a0-5c4a-11e8-9595-e165cd86dbbb.PNG)

**Comment by swdriessen** [comment]
According to Mordenkainen, the Eladrin associated with summer use this word often. Then again, i'm a human so i've corrected it. You won't see the change until the next build though.
