### ISSUE TITLE
Content Request - DND Wiki - Grung 5e Race Variant

### ISSUE THREAD

**Issue by InsanityAtHeart** [aurorabuilder/elements#100]
Hi there me again haha

Just wondering if you could add the playable Grung race from DnDWiki to the race list?

It can be found here: https://www.dandwiki.com/wiki/Grung_(5e_Race_Variant)

If not is there a way I can add it myself?

![grung2](https://user-images.githubusercontent.com/42867626/50380041-86aa6900-06ab-11e9-89d5-61afa6aeae90.jpg)

**Comment by swdriessen** [comment]
I'll add the grung from WotC before adding this. (https://www.dmsguild.com/product/223738/One-Grung-Above-5e)

If you then want the wiki grung it will be easy to copy the file and change it to your liking.

I'm holding off a bit with adding too much homebrew until i release the next version where you can restrict sources for your character so these don't show up unless you want them to.

**Comment by swdriessen** [comment]
I've added the wotc grung from the dmsguild pdf in 817be1f3803bd512ed59d85b99eebfed65f7dd82.

You can try and use the file and change it to include/exclude to reflect the slightly different WIKI variant if you still want that. - reopen if you have any issues
