### ISSUE TITLE
Ravnica Backround Implementation

### ISSUE THREAD

**Issue by MidasTheGolden** [aurorabuilder/elements#101]
I'd like to use this tool to make a ravnica character, but it's missing the backgrounds. Any ideal when the backgrounds will be ready?

**Comment by swdriessen** [comment]
Not yet, what specific background you're looking for? I'll see if i can add it first.

**Comment by MidasTheGolden** [comment]
I'm looking for Izzet Engineer. I'd really appreciate being able to use it. Thank you for all your hard work.

**Comment by swdriessen** [comment]
I've added it, will add others this week.
The guild spells however need some code changes to implement properly. This will be working in the next version (coming sometime later this month)
