### ISSUE TITLE
Content Request - [Bounty Hunter (5e Background)]

### ISSUE THREAD

**Issue by Dablen** [aurorabuilder/elements#103]
**https://www.dandwiki.com/wiki/Bounty_Hunter_(5e_Background)**
Would someone be willing to aadd the bounty hunter background please? Thanks.

**Comment by NickVendel** [comment]
I will add it to my list of future creations.

**Comment by Dablen** [comment]
thanks

**Comment by NickVendel** [comment]
@Dablen Okay, i started Bounty Hunter, but now i have question about features. There's three of them, should this be a choice, is it better to grant all of them, or maybe both (like, one is chosen and others are optional)?

**Comment by swdriessen** [comment]
Merged in #123
