### ISSUE TITLE
Error when loading custom content.

### ISSUE THREAD

**Issue by benfinn** [aurorabuilder/elements#104]
I am receiving the following error when loading the custom content linked below. I ran it through a regular XML parser, and it comes back fine, so I assume this is some problem with the internal schema.

`NullReferenceException with no inner exception: updateNode
Source: Builder.Data
Trace:    at Builder.Data.Files.ElementsFile.PopulateInformationSection(XmlNode infoNode)
   at Builder.Data.Files.ElementsFile.Load(String xml)
   at Builder.Data.Files.ElementsFile.Load()
   at Builder.Data.Files.ElementsFile.FromFile(FileInfo file)
   at Builder.Presentation.Services.Data.DataManager.<InitializeElementDataAsync>d__65.MoveNext()`

[Changeling Custom Race](https://pastebin.com/R9AK9nJV)

**Comment by swdriessen** [comment]
The ```info``` block at the top is used for updating files though the builder. You can leave it out (or comment it out) of custom files that don't use this feature.

Current build is a bit picky about this section when some nodes are left out.

**Comment by benfinn** [comment]
That fixed it, thanks!
