### ISSUE TITLE
House Rules

### ISSUE THREAD

**Issue by benfinn** [aurorabuilder/elements#105]
It might be interesting to allow modifications of the core rules to reflect on the character sheet. For example, in my house rules, your Dex bonus adds to damage with ranged weapons like bows, etc. This could be reflected on the sheet.

**Comment by swdriessen** [comment]
You can make a custom 'Option' that you can select when creating a character or add/remove with existing characters. (It doesn't yet show you have custom/houserule options selected on the sheet.)

The next version will allow you to add your weapon to the attack section and it will auto-calculate the attack and damage. Then you can also increase damage for ranged attacks with some value if you want.

```
<?xml version="1.0" encoding="utf-8" ?>
<elements>
	<element name="Houserule #1" type="Option" source="Houserules" id="ID_HOUSERULES_OPTION_RULE_1">
		<description>
			<p>The DM is always right.</p>
		</description>
		<sheet>
			<description>The DM is always right.</description>
		</sheet>
		<rules>
			<select type="Feat" name="Bonus Feat" level="1" />
			<!-- this basic damage bonus will work in the next version -->
			<stat name="ranged:damage" value="100" />
			<!-- super longbows -->
			<stat name="longbow:attack" value="10" />
			<stat name="longbow:damage" value="25" />
		</rules>
	</element>
</elements>
```

**Comment by swdriessen** [comment]
Not yet, most you can find browsing the files here looking for similar items/features or a quick question can do the trick. I have to rework the statistics a bit soon (case-insensitive and better consistency), after that i'll add some wiki pages here and put up a compiled list of some pre-defined statistic names.

If you're looking for a specific ID from for example a proficiency you could create a secondary shortcut on the desktop and enable ['dev mode'](https://dndbuilder.net/documentation#developer-mode) on it. This will add a button in the statusbar/titlebar that lets you open a window where you can browse loaded elements and see the xml (including a seperate box with the id).

**Comment by benfinn** [comment]
Okay, thank you!
