### ISSUE TITLE
Missing Weapon: Unarmed Strike

### ISSUE THREAD

**Issue by Gherrick** [aurorabuilder/elements#108]
Now that weapons can be added to the character sheet via Equipment tab, I noticed there isn't any option for "Unarmed Strike". Monk's also aren't able to use Dex instead of Str on all monk weapons. It seems Spears and Quarterstaves aren't qualifying, but they should.

**Comment by ColdAnkles** [comment]
Under the Manage tab, there's the attacks section. You can manually add an Unarmed Strike there.
Should Unarmed Strike appear as a default attack, disappearing when you add any others? Or sticking around? There's a bunch of races with natural weapons (claws etc.) that can perform improved unarmed strikes, so it has value in existing.

Can confirm the dex bonus does not appear on spears and q'staves.

**Comment by swdriessen** [comment]
I'll be adding a selection to the attacks to choose and override the ability for calculations. 

I plan to add some basic attacks such as grapple, shove, and also the unarmed. But i also want them to be added from elements either from a race or a companion. So, more improvements in the future.

**Comment by acelegna** [comment]
Any update on this missing feature?

**Comment by swdriessen** [comment]
The override for ability selection on weapons is included. Add attacks from elements directly is not implemented. 

You can create a custom weapon element named unarmed strike (I still might add one but I'm not sure yet) and have this basic result. Otherwise add it manually.

**Comment by acelegna** [comment]
Ok.  That's actually what I've been doing so far.  Just wanted to see if there was an option so that the "weapon" updates the increase damage dice when monk levels up
