### ISSUE TITLE
DawnforgedCast Eldritch Knight (Reforged) Homebrew Archetype

### ISSUE THREAD

**Issue by solo64** [aurorabuilder/elements#11]
I want to make this reimagined archetype for the fighter class because I thought it was really cool and fun to play as. You basically have a mana pool instead of spells and you use points similar to sorcery points to boost your attacks with magic and effects, and you retain some of the features that are present in the original archetype like Weapon Bond.

The pdf that contains the information about that is [here](https://dawnforgedcast.myshopify.com/products/5e-reforged-a-homebrew-guide-for-5th-edition-tabletop-gaming). I have this pdf, but I don't know if I have the legal authority to upload it here because it's a commercial product, so I think I should withhold this file until given the okay. I'm not sure how that stuff works and I'd prefer not to get in any legal trouble, so just playing it safe.

There's also a video showcase about it but I think it's behind the pdf update-wise.
https://youtu.be/5Y7Y7zoQ9A8

**Comment by swdriessen** [comment]
Sure, you can just create it. 

Only link the source when it freely available. The video is fine since you could pause the video and copy over all the content anyway if you wanted to play it.

I suggest you use the `DFC` as the author abbreviation in the ID.
