### ISSUE TITLE
Kensai Proficiency 

### ISSUE THREAD

**Issue by SmogMonster** [aurorabuilder/elements#110]
According to all documentation I can find the race of Changeling selects 2 skills from "Deception, Insight, Intimidation and Persuasion"

Aurora Builder only allows one choice to be made.  Maybe add the ability to add additional Home Ruled proficiencies as the Monk Archetype Kensai grants weapon proficiency for the weapons you choose if you don't already have it.

**Comment by ColdAnkles** [comment]
There are two Changeling races included in the repository. One from the Eberron Unearthed Arcana, the other from The Wayfinder's Guide to Eberron.
The one from Wayfinder has the correct skills as you are describing. Are you selecting the right race from the right source?

According to the Kensei source file
""
This may not be the case any more. @swdriessen  Care to comment?

**Comment by SmogMonster** [comment]
Yes I'm picking the one from The Wayfinder's Guide to Eberron.  the other one doesn't offer any Skills.
When you go to select the choices though it only offers one choice as the picture I've included shows.

![changeling instincts](https://user-images.githubusercontent.com/46771942/51427903-21bf3180-1bcb-11e9-82ff-7ffeb515fcc7.jpg)

 I do understand Kensai being difficult to implement though.

**Comment by ColdAnkles** [comment]
Ah, yeah, I see what you mean.

Line 80 in elements/third-party/dms-guild/wayfinders-guide-to-eberron/races/race-changeling.xml should be select two.

**Comment by swdriessen** [comment]
Fixed the proficiency selection.

I'll have to look into the kensai again, i've made some tests a while back which i'll have to test again.

https://github.com/swdriessen/elements/commit/252d5e306999db713769ef59899324d2b8281914
