### ISSUE TITLE
Incomplete description of Tides of Chaos on the character sheet

### ISSUE THREAD

**Issue by kitterion** [aurorabuilder/elements#115]
The description of the Wild Magic sorcerer's Tides of Chaos on the generated character sheet reads "You can gain advantage on one attack roll, ability check, or saving throw. Once you do so, you must finish a long rest before you can use this feature again." 
It should also mention the ability to regain it with the Wild Magic Surge.

**Comment by swdriessen** [comment]
Thanks, added that part
