### ISSUE TITLE
Missing Chaos Bolt damage types table

### ISSUE THREAD

**Issue by kitterion** [aurorabuilder/elements#116]
The table of the random damage types is missing from the spell card for the Chaos Bolt.
It's in the description of the spell when looking at it in the Magic tab or the Compendium but it doesn't get generated for some reason.

![image](https://user-images.githubusercontent.com/12870762/51435173-c0f33000-1c82-11e9-8611-b69fd0e799d6.png)

**Comment by swdriessen** [comment]
Thanks, it's fixed for the next minor release.

**Comment by swdriessen** [comment]
Fixed in [version 1.19.130](http://dndbuilder.net/releases#119130)
