### ISSUE TITLE
Arcane Artillery

### ISSUE THREAD

**Issue by ColdAnkles** [aurorabuilder/elements#12]
Have forked the repo to work on adding stuff myself, have started with Arcane Artillery (https://www.reddit.com/r/UnearthedArcana/comments/73wjd5/arcane_artillery_the_complete_collection_guns_in/) for use in own upcoming campaign.

If anyone would like to help, check in at my fork...

or whatever it is you do with git - I'm still not sure what I'm doing. #

**Comment by swdriessen** [comment]
Yeah, basicly you fork the repository and create a branch for the changes or addition you want to make. Once that's all done you create a pull request to have those changes merged back into the main project.

(there are a ton of short video's on youtube that go into detail on the process)

You can do it in small bits, for example, the class and some guns first, and expand on it later or take your time and everything at once.

I suggest you create the files as you've already done, add the basic file structure, add xml comments in the files, placeholders with the name of the elements. Like feat x, feat y, feat z to get an overview of what needs to be done. 

Then start with the class before anything else. Maybe add a gun or two to have some items to work with, before adding all things.

Also, just use the all lowercase convention for the files.

- class-gunslinger.xml
- guns.xml
- magic-items.xml
- boons.xml
- artifacts.xml

And think of a good starting ID for your elements
`ID_RDDT_AA` or `ID_RDDT_UA_AA`

**Comment by ColdAnkles** [comment]
In Arcane Artillery the Gunslinger has "Tools: A vehicle or musical instrument of your choice" - I read this to mean you choose between land vehicle proficiency, water vehicle proficiency or proficiency in any one musical instrument.

I think the select should look like this:
<select type="Proficiency" name="Tool Proficiency (Gunslinger)" supports="ID_PROFICIENCY_TOOL_PROFICIENCY_VEHICLES_WATER|ID_PROFICIENCY_TOOL_PROFICIENCY_VEHICLES_LAND|ID_PROFICIENCY_MUSICAL_INSTRUMENT" number="1" />

But it does not work, only giving land and water vehicles as a choice.

What's wrong here?

**Comment by swdriessen** [comment]
I can't see your support string in the comment but this works:
`supports="(Tool,Vehicles)||Musical Instrument"`

**Comment by ColdAnkles** [comment]
That's that solved, but now I'm stuck on doing the ASI feature. I've looked at the existing classes and I have no idea how they work. The IDs that the ASI refers to don't exist anywhere, and attempting to emulate them doesn't work.

What am I missing?

**Comment by ColdAnkles** [comment]
Nevermind, the ASIs work now and I have no idea why :/

**Comment by swdriessen** [comment]
Ah yeah, i auto generate them based on loaded classes since i implemented multiclassing.

Otherwise you'd have to create a lot of elements for ability score increase and feat choice for all kinds of levels which was a little annoying.

**Comment by ColdAnkles** [comment]
Progress Update
Completed:
    Guns
    Ammo
    Gunslinger
    Pact
    Eldritch Invocations
    Feats
Incomplete:
    Magic Weapons
    Artifacts

@swdriessen - is this a good point to merge it into the base? or finish it all off?

**Comment by swdriessen** [comment]
You can create a branch with your content and submit a pull request, i'll hold off merging it and you can commit to the branch and it will update the pull request.

This way me or others can already test things and provide feedback.

**Comment by ColdAnkles** [comment]
I've submitted my pull request #98

**Comment by ColdAnkles** [comment]
#98 is committed in, and I'm putting this on hold - unless anyone else wants to add the few remaining bits.

**Comment by swdriessen** [comment]
You can create a new issue with a todo list in the reddit repo for this, i'll close it here.
