### ISSUE TITLE
Adding Proficiencies, Feats, Languages and Spells whenever

### ISSUE THREAD

**Issue by ThomazM** [aurorabuilder/elements#121]
_(copying it from my own post on r/aurorabuilder)_

### Breaking the rules: Adding stuff when I'm technically not supposed to. Is it possible?

Let's say your dungeon master allows everyone at the table to pick a feat at level five -- just cause he feels like it, or for roleplaying reasons. That's not technically in the book, but it's not too uncommon for a more relaxed table to do something like this from time to time. Maybe my warlock happened to go through just the right experience to unlock a high-level spell NOT in his spell list. Or the party completed a divine mission that got them awarded with whatever. The point is:

- The Builder follows the rules pretty tightly and I understand why. However, I'm curious if there's a checkbox I could uncheck that would disable that, allowing me to add stuff to my character that's not exactly by-the-book, mainly extra spells, feats, languages and proficiencies. If not, I'd love to the see it as a feature one day!

**Comment by NickVendel** [comment]
Again, you can add file with options, even though it's hella harder. It's confirmed that there's going to be in-app function to homerule different stuff, but my guess that it would be implemented close to full release, or after.

**Comment by swdriessen** [comment]
Various elements can be added from the new equipment categories:
https://aurorabuilder.com/posts/977/preview-version-1191216/
