### ISSUE TITLE
Limiting source material selectively.

### ISSUE THREAD

**Issue by benfinn** [aurorabuilder/elements#126]
So, let's say I wanted to make a custom setting, and I didn't want any of the core PHB races, but I wanted the classes and everything else. Is there a way to limit that in a custom file?

**Comment by ColdAnkles** [comment]
Potentially overwrite the race IDs, with elements from another source. Then exclude that source. This isn't really intended I guess. Valid use case though.

**Comment by benfinn** [comment]
Would it be possible to add a tag that does overrides into custom content? Maybe something like this:

`<override id="HOMEBREW_OVERRIDE_ELF" override_id="ID_RACE_ELF">
      <description><p>Ain't no elves in Ben's game, yo!</p></description>
</override>`

And then whatever is in the _override_id_ is simply disallowed, with an optional <description> element to explain why?

**Comment by swdriessen** [comment]
I'd have to look into adding something like this; usually you want this depending on what campaign you create the character for. This way things will override the elf and you'd have to remove the custom file to create an elf again for another campaign.

If you want to fully exclude the elf this should prevent it from showing up in the races selection.

```<element name="Elf" type="Non Existing" source="Player’s Handbook" id="ID_RACE_ELF" />```

Note: `type="Non Existing"` can be anything that's not an actual type. It will still load but it won't find it anymore when looking for races.



Depeding on how much you wanna homebrew things: if you want to fork the repository and homebrew all kinds of the official content exactly how you want it. You could even replace all the url's from `aurorabuilder/elements` to `benfinn/elements`, and make changes just the way you like it. With this control you could remove the original core.index and replace it with your own.


Then, you could add a requirement on the elf element:

```<requirements>!ID_HOUSERULES_OPTION_RULE_2_NO_ELVES</requirements>```

so the elf isn't (!) selectable when you have the houserule option 2 selected

```
<element name="Houserule #2" type="Option" source="Houserules" id="ID_HOUSERULES_OPTION_RULE_2_NO_ELVES">
	<description>
		<p>No elves allowed.</p>
	</description>
	<sheet>
		<description>No elves allowed.</description>
	</sheet>
</element>
```

**Comment by swdriessen** [comment]
I'd most likely be leaning towards expanding the restrictions tab where you can export a certain selection of restricted sources and import them for a character.

You can then send a mycampaignrestrictions.xml to someone and they could apply it to their character. In this file would be a list of restricted sources and IDs.
