### ISSUE TITLE
Rakdos Cultist BG bug

### ISSUE THREAD

**Issue by NickVendel** [aurorabuilder/elements#127]
No matter which spellcasting class are you, if you select Rakdos Cultist and then choose any of the given spells that have duplicate (aka were in class's spell list originally), Aurora crashes.

Few replicating methods: 
Any race > Bard > Rakdos Cultist > Choose Dissonant Whispers spell > Crashes after you choose another spell.
Any race > Wizard (level 3) > Rakdos Cultist > Choose Flaming Sphere spell > Crashes after you choose another spell.
Note: Wizard have Burning Hands originally, after choosing this BG it does not add duplicate spell for some reason.

**Comment by NickVendel** [comment]
label:bug

**Comment by ColdAnkles** [comment]
Line 77 of elements/supplements/guildmasters-guide-to-ravnica/backgrounds/rakdos-cultist.xml is where the Spell table extension is defined.

**Comment by NickVendel** [comment]
I know, but why is it broken though?

**Comment by ColdAnkles** [comment]
commented that in case anyone else wanted to look.

I've done some testing myself, and some of the Rakdos spells cause it, and some don't.

Using a Bard:

So far it's happened to me with the following:
Dissonant Whispers
Crown of Madness
Confusion
Enthrall

Not happened with:
Burning Hands
Fear
Dominate Person
Wall of Fire

Fear and Dominate person are originally Bard spells, but they don't cause a crash (they do duplicate in the list though).

**Comment by NickVendel** [comment]
And for me both of them are crashing Aurora. So i don't know what am i doing wrong what you don't.

**Comment by swdriessen** [comment]
I've fixed it, as in 'it's working for me now', double spells shouldn't appear anymore. I'll test some more to make sure before i release it in the next minor update.

**Comment by pkducklett** [comment]
I'm having a similar issue with the Warlock. Neither cantrips are causing problems, only the spells. I also managed to save my file after selecting one of the spells and now I cannot load that character anymore.

**Comment by swdriessen** [comment]
The background should work with the new version **1.19.130**, give it a go.

**Comment by swdriessen** [comment]
Re-open if any issue persists.

**Comment by NickVendel** [comment]
Yeah, i don't see anything wrong with Bard and Wizard classes, so my guess that it's also fixed for other classes as well.
