### ISSUE TITLE
Pictures and companion pictures

### ISSUE THREAD

**Issue by bestninjastar** [aurorabuilder/elements#128]
i just tried with 6 character sheets and the pictures are not showing up in the PDF version. after i saved the character sheet. but the pictures did show up in the application "aurora builder"

**Comment by NickVendel** [comment]
Strange. It's fine for me. This is happening with all characters? And what app do you use to open PDF?

**Comment by swdriessen** [comment]
Did it work with the preview version?

**Comment by bestninjastar** [comment]
Yes it worked in preview, and I use Google chrome for the pdf

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NickVendel** [comment]
I see, i can confirm that Google Chrome doesn't show pictures. I opened pdf with Firefox and it was fine, same as with using Acrobat.

**Comment by swdriessen** [comment]
If you flatten the pdf (uncheck form fillable in settings) it will show the images. I'll have to do some tests to see if i can solve it, it might put the original box to select an image over the rendered image in browsers.

**Comment by swdriessen** [comment]
It will be displayed correctly in chrome with the next release.
