### ISSUE TITLE
Content Request - Mystic Class

### ISSUE THREAD

**Issue by dailymind** [aurorabuilder/elements#130]
http://media.wizards.com/2017/dnd/downloads/UAMystic3.pdf

Is there any plans for adding in any Unearthed Arcana material? I specifically am trying to create a mystic class, I've used Aurora in the past and love it (more than D&D Beyond most of the time), but Aurora nor D&D Beyond has the class available at the moment.

Thanks,
David

**Comment by NickVendel** [comment]
"any Unearthed Arcana material"? There's lot's of UA files. 
Anyway, Mystic Class uses weird rules in comparison to PHB classes, so there's probably going to be some problems with including this one. If it's possible i will create this one after making [Necromancer Class](https://www.dandwiki.com/wiki/Necromancer_\(5e_Class\))

**Comment by swdriessen** [comment]
Added in #155
