### ISSUE TITLE
Add Pit Fighter To Background 

### ISSUE THREAD

**Issue by applle3** [aurorabuilder/elements#136]
Hello, I would like Pit Fighter to be added as a Background. 
[Pit Fighter.pdf](https://github.com/aurorabuilder/elements/files/2818892/Pit.Fighter.pdf)

**Comment by NickVendel** [comment]
Can you please specify who made this Background?

**Comment by applle3** [comment]
I apologize I don't know where it comes from my DM provided it to me as a background for the campaign we are playing.

**Comment by NickVendel** [comment]
Found it. It's a book "Improved Backgrounds" by the Damion Meany on [dmsguild](https://www.dmsguild.com/product/208784/Improved-Backgrounds). With over 100 pages of Backgrounds. Interesting find i must say, maybe i'll make this one for you, i don't think this is something hard.

**Comment by applle3** [comment]
That would be great and really appreciated.  Thank you,
