### ISSUE TITLE
Content Request - Ability for adding proficiency for backgrounds that have another proficiency source.

### ISSUE THREAD

**Issue by JasperNakamura** [aurorabuilder/elements#139]
In the Players Handbook under Backgrounds it states that 

> Each background gives a character proficiency in two skills... **If a character would gain the same proficiency from two different sources, he or she can choose a different proficiency of the same kind (skill or tool) instead.**

Thus, is it possible to add an option where if there is a skill occupied by a second source that a background skill also has to add a different proficiency?

Thank you for your time, Swdriessen.

**Comment by NickVendel** [comment]
Hmmm... i think this means that you need to change all of the background files to add line which gives this choice. Right now, i think, it's a lot more easier to just choose other Background and then rename your background (in pdf form at least) and/or traits, flaws, bonds and feature to needed ones.

Another way, is just to add your own Background file. I'm going to create one which gives me ability to choose any 2 skills proficiencies and then maybe also another one which gives 2 skills and 1 tool of choice, just so i didn't have to look up needed background/create one every time there's a strange combination.

**Comment by swdriessen** [comment]
Yes, this is something that still needs to be implemented. I'll most likely look at it when i start to implement adding houserules (adding feat/proficiency/spell from UI) as generating the selection is probably very similar.
