### ISSUE TITLE
Suggestion : Easy lvl 1 equipment

### ISSUE THREAD

**Issue by nightwing367** [aurorabuilder/elements#141]
Might be hard with how the data is stored but a way to automatically add all the lvl 1 equipment (class + background) to a character would be nice. Bonus point if it allows you to make the choices (especially from the classes item options). Quick and dirty way : have a button to show the items from both the class and background on the equipment screen. 

Not sure if it's worth the time to invest but I sure would find it useful. I often make many characters (for tinkering about and to help friends)

**Comment by swdriessen** [comment]
Yes, it's something on the todo list.

**Comment by ColdAnkles** [comment]
To that point - exploding "packs". Starting equipment says you get a scholars pack or something similar. Can it get an exploding option where it becomes all of the component parts instead of having "1 scholar's pack" and having no idea how you've used the component parts of it.

**Comment by nightwing367** [comment]
I agree that it would be very useful

**Comment by swdriessen** [comment]
*puts 'exploding packs' on the list*
