### ISSUE TITLE
Archery Fighting Stle

### ISSUE THREAD

**Issue by SmogMonster** [aurorabuilder/elements#149]
According to PHB the Archery Fighting Stlye grants a +2 bonus to Ranged Attacks.  
Unfortunately the coding is putting the bonus into the damage slot of ranged attacks.  
Just an error I think you should be aware of.  You might not the damage is correct in the picture.  I had to adjust that.  The "Archery 2" bonus should be on the attack box.

![archery stle error](https://user-images.githubusercontent.com/46771942/52603192-cbdd5280-2e33-11e9-85a7-bde824849328.png)

**Comment by swdriessen** [comment]
It was fixed with the file updates last month at the time this version was released. Make sure to update the custom files.
