### ISSUE TITLE
Content Request - Awakened Unded

### ISSUE THREAD

**Issue by SmogMonster** [aurorabuilder/elements#150]
Both of these links lead to a homebrew of adding a playable Ghost, skeleton and revenant race.  
If it is possible to add these, I think people would enjoy them.

https://drive.google.com/file/d/0BwF09f1afXWlNWNMWTN3ZVdJTXc/view
https://imgur.com/gallery/4WeXoo2

**Comment by swdriessen** [comment]
reminder for the most recent version: https://www.dmsguild.com/product/222229

**Comment by NickVendel** [comment]
Seen that. Would probably create these races when going to play part 2 of my campaign, because there's some skeleton/zombie NPC's. (Not soon, maybe not even in this year)

**Comment by NobodyisOutis** [comment]
I too would like to have Awakened Undead race. It would be fun
https://www.dndbeyond.com/characters/races/88796-awakened-undead-v-4

This source seems pretty interesting

**Comment by swdriessen** [comment]
It's been merged
