### ISSUE TITLE
new error - have removed the folder in appdata

### ISSUE THREAD

**Issue by cofuzze** [aurorabuilder/elements#151]
having this error - have removed the app data folder - removed the folder in documents and reinstalled. 
Please see images.

Aplication does not start just gives these errors and closes.

![2](https://user-images.githubusercontent.com/11380525/52614197-9408f600-2e99-11e9-8052-a6d482062cee.PNG)
![3](https://user-images.githubusercontent.com/11380525/52614198-94a18c80-2e99-11e9-8359-76fc8bff495b.PNG)
![1](https://user-images.githubusercontent.com/11380525/52614199-94a18c80-2e99-11e9-805e-3183bf780adb.PNG)

**Comment by swdriessen** [comment]
Download version 1.19.130, try and remove the files in **C:\Users\xxxxx\AppData\Local\Builder** folder when the messages are not shown (application not launched). Perhaps after a restart to make sure.

I did find a fix for this issue recently so the next version performs a check at startup to remove the corrupted user settings file automatically should this happen.

**Comment by cofuzze** [comment]
I have tried restarting and switching off my antivirus.  is there anything
else I can try?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cofuzze** [comment]
I have Found it created a folder on my other user. thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
