### ISSUE TITLE
Content Request - Revised Ranger

### ISSUE THREAD

**Issue by nightwing367** [aurorabuilder/elements#165]
Tall order that one but the Revised Ranger is much more interesting that the vanilla one so if you find the time to add him (possibly code needed for the beast?).

https://media.wizards.com/2016/dnd/downloads/UA_RevisedRanger.pdf

**Comment by NickVendel** [comment]
@nightwing367 i sometimes don't understand people.
For one -- #118 
Secondly -- [This](https://www.reddit.com/r/aurorabuilder/comments/aj3rl0/betaversion_of_ua20160912_revised_ranger/)
People, c'mon, it's not that hard to search around.

**Comment by nightwing367** [comment]
hum, guess I'll have to remove all tags from the search bar next time. Didn't remove the issue one and it didn't show up. Thanks for the info

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
