### ISSUE TITLE
Sharpshooter Feat does not display everything correctly

### ISSUE THREAD

**Issue by Zorgalorg** [aurorabuilder/elements#181]
Sharpshooter feat only gives you a quick description of what it would do and not all the details like the damage and additional information concerning it
![capture](https://user-images.githubusercontent.com/47869778/53201064-589dc280-3623-11e9-9ce8-823727b00aa7.PNG)

**Comment by swdriessen** [comment]
I updated all feat descriptions and will be included with an upcoming update soon.

**Comment by Zorgalorg** [comment]
thanks and neet

**Comment by swdriessen** [comment]
It's included in the new updates, v1.19.304

![afbeelding](https://user-images.githubusercontent.com/1596388/53735176-6c002780-3e86-11e9-80b3-1f010e496a40.png)
