### ISSUE TITLE
Can't open installer on Windows 10.

### ISSUE THREAD

**Issue by Matias-Leibo** [aurorabuilder/elements#183]
After dowloading the installer from the official website I just get an error message when I open it (see attached). I've tried downloading it againt and changing the file location, but that hasn't worked. What can I do to solve it?

![image](https://user-images.githubusercontent.com/47900318/53264483-7702cd00-36ba-11e9-8365-a364bc22c513.png)

Error message: This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package.

**Comment by swdriessen** [comment]
The file size should be near 80Mb so the download was incomplete.

**Comment by Matias-Leibo** [comment]
Huh. Alright. I'll see what happens.

**Comment by Matias-Leibo** [comment]
> The file size should be near 80Mb so the download was incomplete. Delete the incomplete file and try one more time.

Alright, that's done it! Tried downloading via ethernet and it's running smoothly. Thanks a ton!

**Comment by swdriessen** [comment]
👍 Have fun!
