### ISSUE TITLE
NPC Statblock Output Format

### ISSUE THREAD

**Issue by DaltonTheDM** [aurorabuilder/elements#184]
I would like to request that an option is made to output any characters made within the Aurora Builder into the standard 5e NPC Statblock format (as found in the Monster Manual or other such locations). Basically, something that trims the fluff and gives me just the raw mechanics.

I am my groups DM and have been using this amazing program to build some NPCs for them to fight and would find this feature extremely helpful. 

Even if this feature is never added this is an amazing Program and I'd like to thank whoever has put the time and effort into making it. 

Thank you
~DMDalton

**Comment by swdriessen** [comment]
Since it's a character builder any DM related features if any are low on the priority list.
