### ISSUE TITLE
Content Request - Theurgist

### ISSUE THREAD

**Issue by Rieleniel** [aurorabuilder/elements#187]
**Source URL**
https://media.wizards.com/2017/dnd/downloads/MJ320UAWizardVF2017.pdf

Is there any possibility of the Theurgist subclass being incorporated into the builder soon? I know it uses weird rules which partly resembles the Divine Soul Sorcerer but not quite, but I hope something can be done about it.

**Comment by NickVendel** [comment]
That's my project today

**Comment by Rieleniel** [comment]
Oh, great! Thank you very much!

**Comment by NickVendel** [comment]
Damn it. I think i need to save this one for last. It has very difficult features. Basically, i need to redo ALL domains for it, it's like Archetype that in itself has all of the Cleric Archetypes. It's too much. 
I'm sorry, i thought it'd be alternative Divine Soul and wasn't ready for this much work.
