### ISSUE TITLE
Content Request - Gemstone Dragonborns

### ISSUE THREAD

**Issue by MarceloPai** [aurorabuilder/elements#195]
https://shop.mcdmproductions.com/products/strongholds-followers-pdf
A link to the source of the requested content. (website or pdf)

**Comment by NickVendel** [comment]
what? You want content from non-released third-party book?

**Comment by MarceloPai** [comment]
Actually this was released already. I have my copy. 
Gemstone Dragons are monsters, but there are rules for the Gemstone Dragonborns as a race.

**Comment by NickVendel** [comment]
> Notification: THIS IS A PREORDER. You will not receive a physical product until they are ready to be shipped in Q2 2019.

**Comment by MarceloPai** [comment]
Well, you're right. But the pdf version is released, just the physical copy that is preorder, I think. I have a copy 'cause i backed up on kickstarter.
I'm attaching the rules I'm talking about.

Really sorry for the mess
![desktop screenshot 2019 02 26 - 09 36 38 35](https://user-images.githubusercontent.com/47994179/53413216-2fc25800-39aa-11e9-8b91-b60a03ff9a37.png)

**Comment by NickVendel** [comment]
I think you just get copy earlier since you backed it. 
Anyway, close this request, i will do file for you and gonna DM it in discord

**Comment by MarceloPai** [comment]
Thanks Nick
