### ISSUE TITLE
Content Request - Ratfolk Race (Homebrew)

### ISSUE THREAD

**Issue by MarceloPai** [aurorabuilder/elements#197]
**https://www.dndbeyond.com/races/9830-ratfolk?fbclid=IwAR2_enO3LZuUIUcy_cDtjc385r6T86Bg8t1umxbTXc2hWMbXVGo9tfAr3qU**

**Comment by NickVendel** [comment]
this is homebrew content for personal use, something like this is usually better to ask about on discord

**Comment by NickVendel** [comment]
Close this request, since @Azzzzzy did it on discord
