### ISSUE TITLE
Impossible select feat after first level 

### ISSUE THREAD

**Issue by Tony1990** [aurorabuilder/elements#20]
As you can see in the image (gif), when the PG reaches the level 4 it's impossible select a feat instead of ability score increase.
![feat_bug](https://user-images.githubusercontent.com/9660402/42186663-cf8dd562-7e4d-11e8-9999-3cae87149333.gif)

**Comment by swdriessen** [comment]
When you go to the class tab you can de-select the ability score increase option and pick feat instead. The ability score increase option is currently selected as default. 

Good change i'll remove the default selection with the next update since it causes some confusion.
