### ISSUE TITLE
Breaking Changes - Upcoming Update

### ISSUE THREAD

**Issue by swdriessen** [aurorabuilder/elements#203]
# Breaking Changes in Upcoming Update
For the upcoming update some changes are required for some elements to work properly.

## Updated Statistic Names
The statistic names will all be lowercase to avoid confusion. Also, use the new replace method (`{{statistic name}}`) to inject a statistic value in the sheet descriptions and the new `action` and `usage` attributes (see details below). This change also applies to the `name-format` setter in races and magic items. Old replace methods will be removed.

If you're interested you can view **[this](https://github.com/aurorabuilder/elements/pull/142)** pull request to see all kinds of changes to the files with the upcoming update.

Where possible the builder will convert the previous statistics name in a statistic rule to the new name in an attempt to allow some unchanged content to be loaded correct. For example: a rule that references the `Strength Saving Throw Misc` will be convert to the new `strength:save:misc`. It will not update the statistic name in the file itself.

#### Abilities
(applies to all abilities, 1 example given)

| Previous | New |
| --- | --- |
| `Strength` | `strength` |
| `Strength Modifier` | `strength:modifier` |
| `Strength Maximum` | `strength:max` |
| `Strength Score Set` | `strength:score:set` |
| {{only replace usage}} | `strength:score` |

#### Saving Throws
(applies to all saves, 1 example given)

| Previous | New |
| --- | --- |
| `Strength Saving Throw Proficiency` | `strength:save:proficiency` |
| `Strength Saving Throw Misc` | `strength:save:misc` |

#### Skills
(applies to all skills, 1 example given)

| Previous | New |
| --- | --- |
| `Acrobatics Proficiency` | `acrobatics:proficiency` |
| `Acrobatics Misc` | `acrobatics:misc` |
| `Acrobatics Passive` | `acrobatics:passive` |

#### Innate Speed (Races)
Speeds with a racial origin now have an *innate* speed statistics.

| Previous | New |
| --- | --- |
| `Speed` | `innate speed` |
| `speed:climb` | `innate speed:climb` |
| `speed:fly` | `innate speed:fly` |
| `speed:swim` | `innate speed:swim` |
| `speed:burrow` | `innate speed:burrow` |

_Use `innate speed:misc` for features such as the monk's unarmored movement that affect all innate speeds_

| Previous | New |
| --- | --- |
| --- | `innate speed:misc` |
| --- | `innate speed:climb:misc` |
| --- | `innate speed:fly:misc` |
| --- | `innate speed:swim:misc` |
| --- | `innate speed:burrow:misc` |

Internally the innate speeds are put together and populate the normal `speed` statistics with a `base` stacking bonus use `innate speed:calculation` to get this value if needed

_Use the `speed:misc` for any additional increases to speeds_

| Previous | New |
| --- | --- |
| --- | `speed:misc` |
| --- | `speed:climb:misc` |
| --- | `speed:fly:misc` |
| --- | `speed:swim:misc` |
| --- | `speed:burrow:misc` |

When you get a swimming speed equal to your walking speed you can still use a statistic such as this one using `base` as the stacking bonus.
```xml
<stat name="speed:swim" value="speed" bonus="base" />
```

#### Miscellaneous Stats
Various statistics.

| Previous | New |
| --- | --- |
| `Proficiency` | `proficiency` |
| `Proficiency Half` | `proficiency:half` |
| `Proficiency Half Rounded Down` | `proficiency:half` |
| `Proficiency Half Rounded Up` | `proficiency:half:up` |
| --- | --- |
| `Initiative` | `initiative` |
| --- | `initiative:misc` |

## Armor Class Caluclation
When adding a bonus to Armor Class that isn't part of the armor calculation or shield you can add it to `ac:misc` so it can be listed on the sheet as additional increases.

| Previous | New |
| --- | --- |
| `AC` | `ac:misc` |
| --- | `ac:shield` |
| --- | `ac:calculation` |

Example of ac calculation for _**Draconic Resilience**_
```xml
<stat name="ac:draconic resilience" value="13" />
<stat name="ac:draconic resilience" value="dexterity:modifier" />
<stat name="ac:calculation" value="ac:draconic resilience" bonus="calculation" equipped="[armor:none]" alt="Draconic Resilience (Sorcerer)" />
```

#### Armored
The base of `10` is no longer included by the builder for the armor, use the total armor bonus from the armor instead (see any of the updated armors)

| Previous | New |
| --- | --- |
| `AC` | `ac:armored:armor` |
| --- | `ac:armored:enhancement` |
| --- | `ac:armored:misc` |

Example for _**Plate**_
```xml
<stat name="ac:armored:armor" value="18" />
```

#### Unarmored
When not wearing armor the internal **Unarmored** calculation (10 + Dexterity Modifier) is used.

## Additional action & usage attributes for sheet descriptions
You can set action and usage attributes if you want to make it easier to glace at features and determine their usage. They can also be used on the `description` node for different action/usage based on level.
```xml
<sheet action="Bonus Action" usage="1/Short Rest">
	<description>You can magically teleport up to 30 feet to an unoccupied space you can see.</description>
</sheet>
```

When using the style formatting sheet the description will be displayed like this for the fey step element:
_**Fey Step (Bonus Action - 1/Short Rest).**_ You can magically teleport up to 30 feet to an unoccupied space you can see.

**Comment by NickVendel** [comment]
hm... are you sure it's a good idea to use bold font for `action` and `usage` attributes, and also putting it in the same sentence with name of the feature?

**Comment by swdriessen** [comment]
I found it's helpful at a glace when it stands out if you're looking for say... a reaction. Also, i can always create a setting to change preference how it's presented.

![desc](https://user-images.githubusercontent.com/1596388/53671008-f8d79500-3c7c-11e9-88ba-5101316cbb7f.png)

**Comment by NickVendel** [comment]
Yeah, I would like it more if it wasn't in bold or maybe separated from feature name somehow. I like that **(Channel Divinity)**, so it's easier to understand from what feature this ability comes from. But for action type and uses. i don't think it's needed to be in bold and right after name of the feature/ability. IMHO.
