### ISSUE TITLE
Infernal Constitution resistances

### ISSUE THREAD

**Issue by Cockie** [aurorabuilder/elements#204]
**Describe the issue**
Picking the feat 'Infernal Constitution' from XGTE (only available for tieflings) should give you resistance to cold and poison, but these resistances are currently not added to the character sheet.

**Additional context**
Logically, they would show up in the "Speed, senses and conditions" box where the normal fire resistance does show up. I assume it has something to do with the fact that no other feat grants resistances, so it may not be supported?
Not a big problem to add it manually, but I'd thought I'd report it.

**Comment by swdriessen** [comment]
It's fixed in the files that will be updated with the next release (next week)

**Comment by swdriessen** [comment]
added in #142 - upgrade to 1.19.304 required
