### ISSUE TITLE
Documentation for the xml files?

### ISSUE THREAD

**Issue by damccull** [aurorabuilder/elements#21]
Is there documentation somewhere for the xml files so we can help participate without having to reverse engineer the system first?

**Comment by chrisjfoss** [comment]
swdriessen has some documentation at https://dndbuilder.net/documentation, though you will find that there are still a lot of cases where you need to examine existing files to find the information you need.  Naming conventions tend to be consistent enough to guess.

I've been thinking about trying to get some community driven documentation started, but I haven't been able to decide where I would put it. In the meantime, https://www.reddit.com/r/aurorabuilder/ is a good place to ask any questions you have about it.

**Comment by swdriessen** [comment]
Yes, as the little note on the docs page indicates best is to find another feature that does something like the one you are trying to implement.

I tried keeping the documentation up to date at the start but the changes during development made it impossible and very counter productive as long as not all xml is final and things get added or changed. 

Github does support WIKI pages that anyone can add/edit so this might be something worth checking out. I have never used these before myself though.

**Comment by damccull** [comment]
@chrisjfoss Why not at ReadTheDocs.org? It's a great place to host documentation and has a sweet format you can use to create it. Alternatively, using wyam.io as a static site generator and creating a companion github project to this one, and use the github static site hosting to host it? I'd be happy to help with either. Is there a discord, slack, or another chat room to talk about it in? Or we could just use this issue.

@swdriessen I've been looking for weapons, armor and equipment in the existing 'elements' but I can't find any equipment listed in the repo! Is it still built in or something?

**Comment by swdriessen** [comment]
@damccull yes, they are currently in the builder itself. You can view them using the developer mode.

I'm working on the new equipment section and the items (including magic items) will be included here when the new update is released.

I've created a chatroom on gitter, use can use your github account to access it. 
https://gitter.im/aurorabuilder

**Comment by chrisjfoss** [comment]
@damcull @swdriessen I joined the chatroom.  Sorry for taking so long, I had expected a notification from github when this ticket was updated, but I never got one.

**Comment by swdriessen** [comment]
Items are now also in the files for use with version 1.18.817

http://dndbuilder.net/releases#118817
