### ISSUE TITLE
Content Request - [Animal Companion]

### ISSUE THREAD

**Issue by NobodyisOutis** [aurorabuilder/elements#217]
Would it be possible to be able to include an animal companion to the character builder? For example how Crital Role`s Tricket is the animal companion to Vex. Thank you

**Comment by NickVendel** [comment]
Trinket*
It's already in app. Vex'ahlia is a Ranger who gets to choose Companion as part of her's Ranger's Companion feature which comes from Beast Master Archetype. So when you have this prerequisite, app will display another tab "Companion", where you can choose one from those which are included with Player's Handbook (right now that's the only source for companions, later this going to be extended).
![Companion Tab](https://user-images.githubusercontent.com/46818179/54085125-abc18600-4342-11e9-8d75-bdff1a4a0088.png)

**Comment by NobodyisOutis** [comment]
oh, ok thank you :)
