### ISSUE TITLE
Arcanist Feat issue when loading Character

### ISSUE THREAD

**Issue by ColdAnkles** [aurorabuilder/elements#223]
Arcanist feat from UA-SkillFeats says, amongst other things:

> You gain proficiency in the Arcana skill. If you are already proficient in the skill, you add double your proficiency bonus to checks you make with it.

If you select Arcana in proficiencies, then select the Arcanist feat, save then load the character, it will unselect the Arcana skill and ask you to repick from the other options. This only appears to occur when reloaded, otherwise the proficiency appears to be doubled as it says.

**Comment by NickVendel** [comment]
Is it the same for other Skill Feats?

**Comment by ColdAnkles** [comment]
That'd make sense, a race feat being evaluated before other stuff.

On an not unrelated note, Arcanist also gives you Prestidigitation and Detect Magic, which show up in the spell cards, but not the spell lists on the character sheet.

![image](https://user-images.githubusercontent.com/13864745/54424363-a4471600-4762-11e9-82ec-c88df38f314b.png)

**Comment by NickVendel** [comment]
That's normal, since it's not related to your class

**Comment by ColdAnkles** [comment]
While I think this makes sense for features that are along the lines of "use this feature to cast a spell some number of times per long/short rest" - as in you don't cast via normal spellcasting rules.

Arcanist just gives you the spells to be cast via normal rules (though you do get a free use of Detect Magic per long rest).

The language is usually something like "you learn this spell" or "know this spell" instead of "you can cast this spell" - contrast High Elf <i>Cantrip</i> and Drow <i>Drow Magic</i>

This might require extra work, since according to Sage Advice on the Magic Initate Feat (http://media.wizards.com/2015/downloads/dnd/SA_Compendium_1.01.pdf, Page 3) - If you learn a spell from a feat or other source, and it's learnable to your class under normal circumstances (Detect Magic is on the Sorceror list) you can cast it with your spell slots. If it wasn't on the Sorceror list it'd be restricted to the one free cast (and therefore shouldn't appear in the spell lists).

**Comment by NickVendel** [comment]
I kinda agree with you. But, i'm just saying that, app doesn't have a way to recognize spellcasting for feat (at least, i think it doesn't). Maybe you could do some requirements or selection, but i don't think that's ideal. But the same as with #234, @swdriessen should look into creating some kind of way to do this.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
