### ISSUE TITLE
Draconic Language

### ISSUE THREAD

**Issue by BrentKappa** [aurorabuilder/elements#226]
Draconic option not available for "starter languages"

Making a Human "Noble" should allow for two opportunities to choose the draconic language, not available for either. 
![Screenshot](https://user-images.githubusercontent.com/48580341/54411072-1bb87d80-4742-11e9-9a1b-bdb9fd6d9239.png)

**Comment by NickVendel** [comment]
That's because Draconic is not Starter Language

**Comment by BrentKappa** [comment]
Correct, I should have worded the issue better. I was referring to "Starter Languages" as available options for both Human and Noble, not Standard languages. As each state "One of your choice", Exotic languages are still available options.

Ex. Starter set Human Fighter, Noble speaks Common, Dwarvish & Draconic.

**Comment by BrentKappa** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/48580341/54482958-ab277300-489f-11e9-9413-39ee202ed0ed.png)

**Comment by NickVendel** [comment]
They're not by default. And it doesn't matter what Background you are. They all have no specified language.
![изображение](https://user-images.githubusercontent.com/46818179/54509259-a7ecbf80-4951-11e9-8b8d-f70709ebd5da.png)
So if you want to use optional "choose any language" rule, then you need to change files on your own, later there maybe will be in-app Character Option for this.

**Comment by NickVendel** [comment]
@swdriessen I think you can close this issue now
