### ISSUE TITLE
Could you please update the hammer of thunderbolts

### ISSUE THREAD

**Issue by Claymaver2000** [aurorabuilder/elements#228]
**Describe the issue**
The hammer of thunderbolts requires attunement, but on aurora it doesn't so the modifier for it (+4 to strength) isn't added to the sheet. could you please update it so the modifier is applied.

**Additional context**

**Comment by NickVendel** [comment]
To be clear, it's not that it doesn't gives +4 to strength because of attunement. It's because it doesn't give it at all. I will fix that, though there's no requirement for attunement right now, so it'll allow attunement without belt and gauntlets.

**Comment by Claymaver2000** [comment]
Thanks, other then that this is an awesome programs

**Comment by swdriessen** [comment]
Merged.
The requirements aren't active on the weapon yet since you don't have to be attuned to the gauntlet/belt, they just have to be equipped. Needs changes to code.
