### ISSUE TITLE
Custom race crashing for unknown reasons

### ISSUE THREAD

**Issue by prismanticmasque** [aurorabuilder/elements#229]
Hello there, I could use some help. 

After editing a D&D wiki homebrew race, the Embodied Mouther, with balancing help from Reddit, I wanted to implement it into my favourite D&D Character creator. 

I've put a couple custom races in but this race had a few new obstacles like innate proficiency and the human variant trait of choosing an ability score. After a few trial and error attempts I thought everything was progressing but instead of the usual error line that pops up when trying to load the race file it instead immediately crashes with no error message. I'm stumped on what to do and I'll hate myself if it's something stupid. I have absolutely zero coding knowledge and usually blunder through these things via trial and error. My code (if you can call it that) is not usually tidy or the most logical even if it does eventually work as it's always reverse engineered from already implemented races. In this case it was the human race file that I heavily edited.

Could someone please come put me out of my misery and tell me the answer? 

Thanks
[EmbodiedMouther.zip](https://github.com/aurorabuilder/elements/files/2973231/EmbodiedMouther.zip)

**Comment by NickVendel** [comment]
Try this version, if it's not working then be sure that you're updated to .308 version of app
[EmbodiedMouther.zip](https://github.com/aurorabuilder/elements/files/2974139/EmbodiedMouther.zip)

**Comment by prismanticmasque** [comment]
Thanks so much, it's fixed now! What was wrong with it?

**Comment by prismanticmasque** [comment]
Hmm I have the latest version of aurora if that's what you mean? It still doesn't work and now it crashes even when I remove the custom race. Any idea whats going on?

**Comment by prismanticmasque** [comment]
Thanks for the help! It still didn't work but after searching on Reddit it turns out the race wasn't the problem but the program itself. I had to delete the contents of the builder file in APPDATA/Local. Thanks anyway though.

**Comment by NickVendel** [comment]
Yeah, it was weird, because it seemed fine for me, the only part that i actually changed is the name section. But i doubted that it was the problem. Few other people also have a problem with appdata/local files. Also wanna say that you did good job editing human race (which is pretty obvious, to be honest), but still great job. Anyway, good luck and please don't forget to close this issue.

**Comment by prismanticmasque** [comment]
Sorry forgot to close it 😅
