### ISSUE TITLE
Mystic class

### ISSUE THREAD

**Issue by matlem** [aurorabuilder/elements#23]
Is the mystic class implemented?

**Comment by swdriessen** [comment]
There is no mystic class in this collection at the moment.

Do you have a link to the class you're referring to?

**Comment by chrisjfoss** [comment]
I think I found the mystic class [here](http://media.wizards.com/2017/dnd/downloads/UAMystic3.pdf).

**Comment by matlem** [comment]
Yes that is the class I am looking for

**Comment by chrisjfoss** [comment]
@matlem There is not currently support for the mystic class unfortunately.  swdriessen will probably mark this ticket as a content request and somebody should hopefully pick it up and add in the content.

If it doesn't look like anyone else is going to take it, I might do it myself. I am a little slow in getting out the material I commit to though (life is busy), so for something with this much content I prefer to wait to see if anyone else is willing to do it.

**Comment by swdriessen** [comment]
I'm currenly focussed on equipment myself so i have no time at the moment for such a large file.

**Comment by Omenreaper** [comment]
I could do it if I knew where you write your codes.
And for free since no point in worrying about.

**Comment by Fog6532** [comment]
@Omenreaper Have you started working on this? If not I could probably do it.
