### ISSUE TITLE
Content Request - Transmutation Alchemist 2.0

### ISSUE THREAD

**Issue by ItWasTheEgg** [aurorabuilder/elements#237]
**Source URL**
https://dandwiki.com/wiki/Transmutation_Alchemist,_variant_2.0_(5e_Class)

**Comment by NickVendel** [comment]
Wow, that's almost what i wanted to create, but without actual Fullmetal Alchemist stuff, just similar.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
