### ISSUE TITLE
Druid spells cards are missing from the character sheet

### ISSUE THREAD

**Issue by lastis** [aurorabuilder/elements#24]
Only cantrips are shown.

**Comment by chrisjfoss** [comment]
This is the same problem as issue #16, although I'm not sure if that issue should have been closed yet. Regardless, quoting myself from there:
>I believe this is a known issue, I remember seeing it discussed elsewhere, but I can't find it right now.
>
>I think this occurs because of the way the spells are applied to the cleric. Light, Mending, Spare the Dying, etc show up because you were granted knowledge of them through your specific domain. Clerics as a whole however get immediate access to the entire cleric spell list whenever they reach the appropriate level, and however this is handled, it is not creating the spell cards.
>
>This would also be why the issue only occurs for those classes that get immediate access to the whole spell list, such as clerics and druids, as opposed to wizards which have to specifically choose which spells from the list they want to learn when they level up.
>
>I don't personally know of any workarounds for this, short of possibly going into the markup for the cleric class or the grave domain and granting yourself each spell individually.
>
>I believe swdriessen is planning on reworking the pdf generation at some point after he implements the support for equipment, but I have no clue on when that is planned to occur.

I still don't know where I had seen it discussed before..

**Comment by swdriessen** [comment]
Prepared spells don't show up at the moment, will be fixed with next update.

I'll leave this issue open for reference then until i release the next update.

**Comment by swdriessen** [comment]
Give the new version a try, re-open if there are any issues.

http://dndbuilder.net/releases#118817
