### ISSUE TITLE
Sorcerous Origin: Inner Darkness

### ISSUE THREAD

**Issue by The-Spooky-Dude** [aurorabuilder/elements#240]
**Source URL**
http://db4sgowjqfwig.cloudfront.net/campaigns/147874/assets/666736/Class_Sorcerer_Origin_Inner_Darkness.pdf

**Comment by swdriessen** [comment]
You can create requests for Reddit (if it was ever posted there not sure due to lacking source) in the appropriate repository instead.

https://github.com/community-elements/elements-reddit

Learn More: https://aurorabuilder.com/posts/891/community-driven-content-reddit/
