### ISSUE TITLE
Islander Background

### ISSUE THREAD

**Issue by N0llie** [aurorabuilder/elements#25]
Could the Islander background be added to the builder?
Also I followed along another background and (possibly) already made the background but I've never really done anything like this so I dont know if what I have is useless or not.
[Here](https://www.dandwiki.com/wiki/Islander_(5e_Background)) is the background URL.
Let me know if I should upload the xml file I did for the background if that would help.

**Comment by swdriessen** [comment]
You can test what you've made by putting the file in the custom folder. If there are no errors at startup it should be in the list of background when you create a character.

Make sure to give unique ID's to your elements so they won't override existing ones if you copy pasted from another background.

You can post a link to your file if you need some specific help if it's not working.

**Comment by swdriessen** [comment]
I've added the background: https://github.com/aurorabuilder/elements/blob/ad872e0bc836e69c700f0fb4bbeae88c4cb8b2e8/third-party/dnd-wiki/backgrounds/background-islander.xml

You can compare it with your version if you want to try to create another background in the future.
