### ISSUE TITLE
Content Request - UA - Revised Artificer

### ISSUE THREAD

**Issue by fel0pez** [aurorabuilder/elements#273]
https://media.wizards.com/2019/dnd/downloads/UA-Artificer-2019.pdf
[UA-Artificer-2019.pdf](https://github.com/aurorabuilder/elements/files/3051139/UA-Artificer-2019.pdf)

**Comment by Azzzzzy** [comment]
Its been made but still being tested.
[Revised Artificer.zip](https://github.com/aurorabuilder/elements/files/3051145/Revised.Artificer.zip)

**Comment by fel0pez** [comment]
Awesome, thank you!

**Comment by swdriessen** [comment]
It's merged.
