### ISSUE TITLE
Flash Current Selection on multiple clicks of Next Selection

### ISSUE THREAD

**Issue by Isvan** [aurorabuilder/elements#275]
Currently having to help my very clueless players who cant seem to see the selection boxes.

Feature would simple be to flash the focused selection box when they click the "Next Selection" button multiple times in a short time

**Comment by NickVendel** [comment]
What? Can't they just use flow?

**Comment by Isvan** [comment]
Because they got stuck and didn't understand that they still have to select something even if there is only one option. 

It happened with 2/5 players so I can only assume it will happen with other people who are still new to using Aurora

**Comment by NickVendel** [comment]
I repeat, can't they use **flow**, which won't move on, without selecting anything.

**Comment by Isvan** [comment]
Unfortunately because they think something went wrong and break away from the flow and go to another section by them selfs. Its a case of the software works, but the person doenst know how to use it properly. 
I took a look and only now noticed that it says in text in the bottom left what to actually do, but its easy to miss. Especially for first time users

**Comment by NickVendel** [comment]
I mean, i never against any new feature, as long as it's an option. I wouldn't like random flashes, without ability to disable them.

**Comment by swdriessen** [comment]
It's still the experimental first version, the auto flow is disabled by default for this reason. 'Next' doesn't skip it just goes to the first non-optional selection each time it's clicked.

Currently the bar in front of the selection flashes to indicate the next required selection, i've tested a few version with popups but they were all too obtrusive. Flashing the entire selection doesn't have my preference.

It's currently in the statusbar but will get a more prominent spot in future builds. At some point it will also include other required tasks such as ability score selection.
