### ISSUE TITLE
Magical Secrets & Bard Spells Known

### ISSUE THREAD

**Issue by TrikkiNikki** [aurorabuilder/elements#280]
As the program is right now, whenever you get magical secrets, you get two spells from magical secrets and two from the normal bard spellcasting. However, magical secrets does count against spells known, so the only spells you learn at 10th, 14th, and 18th level are the magical secrets spells. This is different for the 6th level ability of College of Lore, which gives two magical secrets spells that do NOT count against spells know.

Because I attempted to understand how to do this and failed pretty badly, I will now ask someone to take time out of their precious day to do it for me because I'm a huge jerk. But jokes aside, if/when someone could fix it, that would be greatly appreciated on my end. Thanks!

**Comment by NickVendel** [comment]
Hm, so you saying that Bard needs to lose spells that they learn at level 10, 14 and 18, since they get to choose them only from Magical Secret feature, and not from class itself?

**Comment by TrikkiNikki** [comment]
That is correct.

**Comment by swdriessen** [comment]
Nick's fix is merged, thanks.
