### ISSUE TITLE
Minor Issue - Hexblade's Curse

### ISSUE THREAD

**Issue by vertigo72** [aurorabuilder/elements#283]
In the sheet description of the Hexblade's Curse it states you "Choose one of the following effects:". From the full description, you do not get to choose one of the effects, but you get all of them. "You gain the following benefits:" is probably more accurate.

**Comment by swdriessen** [comment]
I've updated the description. 
Thanks.

6087463bb8d6f22e4dfdcd06817ffd2dabf1631d
