### ISSUE TITLE
Minor Issue - Missing Action and Usage Tags

### ISSUE THREAD

**Issue by vertigo72** [aurorabuilder/elements#284]
I noticed that some of the sheet descriptions are missing their action and usage tags. I am sure this list is not perfect, but I hope it helps:

class-barbarian.xml
Intimidating Presence - should have action="Action"
Retaliation - should have action="Reaction"
Totemic Attunement (Wolf) - should have action="Bonus Action"

class-bard.xml
Countercharm - should have action="Action"
Cutting Words - should have action="Reaction"

class-cleric.xml
Divine Intervention - should have action="Action"
Read Thoughts - should have action="Action"
Warding Flare - should have action="Reaction" and usage="{{warding flare:count}}/Day"
Corona of Light - should have action="Action"
Master of Nature - should have action="Bonus Action"
Blessing of the Trickster - should have action="Bonus Action"

Note: Improved Duplicity has "AYou" instead of "You"

class-druid.xml
Wildshape - should have action="Action" and usage="2/Short Rest"

class-fighter.xml
Protection - should have action="Reaction"
Feinting Attack - should have action="Bonus Action"
Rally - should have action="Bonus Action"
Riposte - should have action="Reaction"

class-monk.xml
Deflect Missiles - should have action="Reaction"
Slow Fall - has usage="Reaction", should be action="Reaction"
Stillness of Mind - should have action="Action"
Empty Body - should have action="Action"
Shadow Arts - should have action="Action"
Shadow Step - should have action=" Bonus Action"
Cloak of Shadows - should have action="Action"
Opportunist - should be action="Reaction"
Elemental Attunement - should have action="Action"
Fist of Unbroken Air - should have action="Action"
Shape the Flowing River - should have action="Action"
Water Whip - should have action="Action"

class-paladin.xml
Lay on Hands - should have action="Action"
Cleansing Touch - should have action="Action"
Elder Champion - should have action="Action"
Soul of Vengeance - should have action="Reaction"
Avenging Angel - should have action="Action"

class-ranger.xml
Primeval Awareness - should have action="Action"
Volley - should have action="Action"
Whirlwind Attack - should have action="Action"
Stand Against the Tide - should have action="Reaction"
Uncanny Dodge - should have action="Reaction"
Exceptional Training - should have action="Bonus Action"

class-rogue.xml
Cunning Action - should have action="Bonus Action"
Uncanny Dodge - should have action="Reaction"
Versatile Trickster - should have action="Bonus Action"
Spell Thief - should have action="Bonus Action" and usage="1/Long Rest"

class-sorcerer.xml
Draconic Presence - should have action="Action"
Bend Luck - should have action="Reaction"

class-warlock.xml
Gaze of Two Minds - should have action="Action"
One with Shadows  - should have action="Action"
Misty Escape - should have action="Reaction"
Entropic Ward - should have action="Reaction"
Create Thrall - should have action="Action"

class-wizard.xml
Projected Ward - should have action="Reaction"
Minor Conjuration - should have action="Action"
The Third Eye -  should have action="Action" and usage="1/Short Rest"
Hypnotic Gaze - should have action="Action" and usage="1/Long Rest"
Instinctive Charm - should have action="Reaction"
Malleable Illusions - should have action="Action"
Illusory Self - should have action="Reaction"
Command Undead - should have action="Action"
Master Transmuter - should have action="Action"

Note: Projected Ward has "Ehen" instead of "When"

eldritch-invocations.xml
Maddening Hex - should have action="Bonus Action"
Relentless Hex - should have action="Bonus Action"
Tomb of Levistus - should have action="Reaction"

monk-sunsoul.xml
Sun Shield - should have action="Reaction"

paladin-conquest.xml
Invincible Conqueror - should have action="Action" and usage="1/Long Rest"

paladin-redemption.xml
Aura of the Guardian - should have action="Reaction"

ranger-horizonwalker.xml
Planar Warrior - should have action="Bonus Action"
Spectral Defense - should have action="Reaction"

sorcerer-divinesoul.xml
Otherworldly Wings - should have action="Bonus Action"
Unearthly Recovery - should have action="Bonus Action"

warlock-celestial.xml
Healing Light - should have action="Bonus Action"

warlock-hexblade.xml
Hexblade's Curse - should have action="Bonus Action" and usage="1/Short Rest"
Armor of Hexes - should have action="Reaction"

wizard-warmagic.xml
Arcane Deflection - should have action="Reaction"

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
