### ISSUE TITLE
localization of content files

### ISSUE THREAD

**Issue by Fenaldar** [aurorabuilder/elements#289]
Is there any plan to localize anything?
We have only German speaking Player, so I want to localize the content core files.
What's the best way to do?

**Comment by swdriessen** [comment]
I have no plans to localize any content.

If you want to create a localized version of the files it's best to create your own repository/fork. You can localize the descriptions and sheet descriptions and manage it.

You can also just manage it local or host files somewhere else, you don't have to use github.
