### ISSUE TITLE
Artificer: Skills 

### ISSUE THREAD

**Issue by Omenreaper** [aurorabuilder/elements#29]
It immediately picks persuasion and doesn't give the option for slight of hand.
giving the option of two when it should be three and you're down a skill.

**Comment by swdriessen** [comment]
The skill proficiency has been fixed: 5d761ea

I'm not sure about the Persuasion issue, can you give some more details?

**Comment by Omenreaper** [comment]
when i checked my skills on the Character Sheet it immediately checked persuasion instead of giving me a choice

**Comment by swdriessen** [comment]
I guess it comes from background or racial trait, there is no mention of persuasion in the artificer class.

**Comment by Omenreaper** [comment]
It did and i didn't spot it sorry
