### ISSUE TITLE
Feature & Traits: Some strangeness/bugs with Arcane Trickster & Warforged.

### ISSUE THREAD

**Issue by ThomazM** [aurorabuilder/elements#293]
![image](https://user-images.githubusercontent.com/8458910/56388994-d1be2e00-61fe-11e9-8f07-f4ba5259ddba.png)

As you can see in the screencap above, there are a couple of bugs. In order from top to bottom:

1. Under "**Integrated Protection**", the descriptions for the Darkwood Core, Composite Plating and Heavy Plating are all missing and bugged.
2. Under "**Sneak Attack**", a similar bug. Not showing the sneak attack stats and displaying what appears to be code.
3. Under "**Mage Hand Legerdemain**", all of its "additional tasks" which are supposed to be listed below it are missing.

**Comment by NickVendel** [comment]
Do you use old version of app?

**Comment by NickVendel** [comment]
`{{stat name here}}` is the new version of stat inclusion, previous one `%stat name here%` was replaced after 1.19.305

**Comment by ThomazM** [comment]
Didn't realize I hadn't installed the newest version! Sorry for the inconvenience, it's fixed now.

**Comment by ThomazM** [comment]
Just realized the "Mage Hand Legerdemain" are still not showing up.
![image](https://user-images.githubusercontent.com/8458910/56474115-a1b79a80-644b-11e9-80b1-27fb90131947.png)

**Comment by NickVendel** [comment]
It displays correctly, it just doesn't have proper description, i will create pull to fix this.
