### ISSUE TITLE
Content Request - [Artificer by xp to lvl 3]

### ISSUE THREAD

**Issue by worldbol** [aurorabuilder/elements#294]
**Source URL**
Hello, 
I have recently enjoyed the aurora builder but wanted to try and add this version of the artificer. I was hoping someone could help me explain how t implement it or perhaps even do it themselves.

With friendly regards,
Worldbol
A link to the source of the requested content. (https://drive.google.com/file/d/1jeqp5Ls9paEh0yZ0vyhJRoNKCJ4yARf2/view)

**Comment by NickVendel** [comment]
Easiest way to add something in, is to just copy similar file from somewhere under `custom` folder and edit it to suit your needs, then save that file in `custom` root or in user folder

**Comment by ShadowLinks** [comment]
Yeah, you'll probably want to grab the old or new artificer files
(https://github.com/aurorabuilder/elements/blob/master/unearthed-arcana/2017/20170109.xml)
(https://github.com/aurorabuilder/elements/blob/master/unearthed-arcana/2019/20190228.xml)
as a base and start making changes.

As Nick said just save it in the Documents\5e Character Builder\custom folder.
The builder does some checks for the file when it boots and will give you an error message if there's any major issues.
