### ISSUE TITLE
Spells granted by race or subrace aren't reflected in the spells list in the character sheet

### ISSUE THREAD

**Issue by xosancho** [aurorabuilder/elements#30]
Description:
Spells which are granted by a race or subrace don't appear to get added to the character sheet. When selecting spells, the spells are properly not shown as selectable.

Examples:
Protector Aasimar light cantrip
Dark Elf Dancing Lights Cantrip

Setup:
Download Aurora Builder 1.18.511
Launch, go to custom content
Download core via the link, update and reboot
Download supplements via the link, update and reboot.

Repro:
Create a new character
Select Aasimar / Protector
Choose Sorcerer (any spellcasting class) \ draconic bloodline \ acid
(you can now jump to the character sheet and see no cantrip added to spells)
Choose any background, ideals, proficiencies, etc until you get to spellcasting
In spellcasting, note that the cantrip does not appear in selectable spells
Choose spells
Generate a character sheet.

Result:
Light cantrip (from light bearer) is shown in the features and traits, but is not added to the cantrips list in the spell sheet.

**Comment by swdriessen** [comment]
Thanks for the feedback. I'll address this after the equipment update.

Main reason i left these in feature description is that it would require a new single spellcasting page (which are dedicated/class) for 1 or 2 racial spells which is not very efficient.

I'm looking at some alternative sheets or custom page where i can list all spells grouped by class followed by all other spells.

**Comment by QuantumOwl** [comment]
The way I do this is after generating the pdf I add them to the spellcasting page of the class that I have the most levels in.

**Comment by ColdAnkles** [comment]
I brought this up in #223 not realising there was an issue for it.

In my opinion spells shouldn't appear in the spellcasting list if you don't cast them with spell slots.
