### ISSUE TITLE
Stuffs to Aurora Fuction

### ISSUE THREAD

**Issue by Nesshi** [aurorabuilder/elements#306]
Hello,

First of all, I would like to congruence with the software.
Aurora not only has a wonderful layout, but also offers great support for masters and gamers.
I spent a bit of time to learn how I use it, but the experience was worth it.

Well, I'd like to ask him some things (if I may).
It would be great if it'd have an easier way to create personal resources through Aurora, such as OrcPub, Squire and other similars softwares already do. These features I would like to use in my campaigns would be: languages, races, subraces, archetypes, spells, monsters, classes, items, talents (with pre requisites), combat maneuvers, and class options player can choose between two or more features for his character)

That's because whem we need some stuff, it's necessary to create a Issue/Request here in Github to get some things up to date on Aurora. And this can take a lot of time and overwhelm you with "simple things".

If you will allow me, the OrcPub system suggests good ways of doing it. You could have some ideas studying it and implement them to your software.

OrcPub (know DnD Vault) is good, but I believe Aurora is better and I would like to use it whenever possible instead of OrcPub or another system.

Another feature that would be interesting to have in Aurora, would be the control of Encounters and Combat, so that the DM did not get lost amid the many chips of creatures and characters.

**Comment by NickVendel** [comment]
1. I confused about wording, but my guess is that you trying to say "I want ability to include homebrew content without waiting for repository updates". Well, you can do this through .xml files, you can create any of those things you said (except for monsters, more info in 2.). Right now there's no "easy way" to do this, but it will later, somewhere around 1.0 version. App has only one developer, so process is slow but steady.
2. Developer (@swdriessen) said on multiple occasions that DM features (like Combat Tracker or Bestiary) are either less prioritized than other ones, or won't be included at all, since Aurora mostly focused to help players with characters, than DMs with their campaigns. In theory monsters can be created already, but they're only used for Companions, and probably always will be.

If you looking for good Combat Tracker, i personally recommend [Improved Initiative](https://www.improved-initiative.com/), it's very user-friendly and have linked UI for DMs and Players.

**Comment by Nesshi** [comment]
Hello, friend
Thank you by the prompt answer.
Sorry for my mistakes, I'm not so good in English... so it may have somes incorrect expressions on my part.

And too sorry for I have demanded more than I "could".
I wasn't aware that you were the unique developer in Aurora project. After all it's so good that it seems to have been developed by a huge staff.

Well, your guess is correct. I would like to create my own homebrew but not "easier" in the meaning "do not want to have any work" but "easier" in the meaning "do not overload Aurora developer".

Do you have any model of this .XML and tips about how I can export in compatible file with Aurora (.INDEX)? Sorry if I'm demand more of you again, I'm not developer and just want to be a good DM for my player.

Anyway, thanks for your attention and support.
I'd like to make a donation to the project, but I don't  know which value would be ideal. I wouldn't like to make insignificant (enough to buy only a cup of coffee) value, but I also can't donate a huge amount due to currency values, once the money of my country (Brasil) is four times lesser than the Euro.
What amount could I donate to the project without seeming offensive?

Thank you again

---


Atenciosamente

[Portifólio Online: Nesshi S. Oliveira (Behance)]<https://goo.gl/nQhaxx>

________________________________
De: NickVendel <notifications@github.com>
Enviado: quinta-feira, 16 de maio de 2019 09:24
Para: aurorabuilder/elements
Cc: Nesshi; Author
Assunto: Re: [aurorabuilder/elements] Stuffs to Aurora Fuction (#306)


  1.  I confused about wording, but my guess is that you trying to say "I want ability to include homebrew content without waiting for repository updates". Well, you can do this through .xml files, you can create any of those things you said (except for monsters, more info in 2.). Right now there's no "easy way" to do this, but it will later, somewhere around 1.0 version. App has only one developer, so process is slow but steady.
  2.  Developer (@swdriessen<https://github.com/swdriessen>) said on multiple occasions that DM features (like Combat Tracker or Bestiary) are either less prioritized than other ones, or won't be included at all, since Aurora mostly focused to help players with characters, than DMs with their campaigns. In theory monsters can be created already, but they're only used for Companions, and probably always will be.

If you looking for good Combat Tracker, i personally recommend Improved Initiative<https://www.improved-initiative.com/>, it's very user-friendly and have linked UI for DMs and Players.

**Comment by NickVendel** [comment]
**I'm not a developer**, @swdriessen is the only one who working on the app. I'm just contributor of content here and ~unofficial community manager~ regular user of the app.
There's no .xml model per se, but you can open any file, copy content and create your own files based on original ones, at first it seems more hard than it is. If you want to share your files, you can either just post them anywhere online wherever you want, or alternatively you can create repository here, on github, then make an .index file (with links in it to your content) and, basically, share content the same way this repository shares it, through in-app downloading of .indexes. Second one is kinda convoluted, and requires time to set-up and learn how things work.
About donation, if you care to give developer money, then give what you want and/or can give, amount shouldn't matter. I'm personally didn't give a single penny to this project, but in my eyes, the more people like, i and @Azzzzzy do content, the less it goes on dev's shoulders.
