### ISSUE TITLE
Content Request - DND Wiki - Apeling

### ISSUE THREAD

**Issue by ArturMorgen** [aurorabuilder/elements#308]
https://www.dandwiki.com/wiki/Apeling_(5e_Race)

I wanted to try and make a character with the Apeling Race and I have tried working on my own files to add to the builder. This is what I managed to get for the race file, but I haven't figured out subclass files and how to add it into index to put on the builder.

https://raw.githubusercontent.com/ArturMorgen/D-D_Homebrew/master/race-apeling.xml?token=AMDCPZ2XVPCZQ57OM64R42S44ACM6

**Comment by ArturMorgen** [comment]
The subclasses and other information I was referring to was actually found here:
https://www.dndbeyond.com/races/13709-apeling

**Comment by NickVendel** [comment]
...um, link goes nowhere.

**Comment by ArturMorgen** [comment]
I changed the folder to public. You should be able to see both the race xml file and index file

**Comment by ArturMorgen** [comment]
https://github.com/ArturMorgen/D-D_Homebrew

**Comment by NickVendel** [comment]
Well, use to make a **subrace** you need to create trait for race, that gives `<select type="Subrace" supports="Apeling">` and then create similar to race elements with `type="Subrace"` and `<supports>Apeling</supports>`, check original races for more reference.
Example from my own race:
```xml
<grant type="Racial Trait" id="ID_NV_BDTD_RACIAL_TRAIT_HAG_TYPE" /> <!-- this goes into race element -->

<element name="Hag Type" type="Racial Trait" source="Bladetide Setting" id="ID_NV_BDTD_RACIAL_TRAIT_HAG_TYPE">
	<sheet display="false" />
	<rules>
		<select type="Sub Race" name="Hag Type" supports="Hag Type" />
	</rules>
</element> <!-- trait element with a select -->

<element name="Island Hag" type="Sub Race" source="Bladetide Setting" id="ID_NV_BDTD_HAG_TYPE_ISLAND_HAG">
	<supports>Hag Type</supports> <!-- subrace element that has proper support --> ```

**Comment by ArturMorgen** [comment]
What do I need to do to fix the main race first?

**Comment by NickVendel** [comment]
what the problem with it?

**Comment by ArturMorgen** [comment]
I can't upload the index file onto the builder, and I'm not sure if it's an issue with the .index file or the .xml file

**Comment by NickVendel** [comment]
Um... yeah, i think the problem is with the link you have for both .index and race file inside your index.
I'm really don't know much about .index, but i think it uses this structure:
`https://raw.githubusercontent.com/[user-name]/[repository name]/[branch name]/[file or folder inside repository]`

**Comment by swdriessen** [comment]
Yes, to load the content through the index file you need to use the correct urls

the url to your index: `https://raw.githubusercontent.com/ArturMorgen/D-D_Homebrew/master/best-class.index`
apeling url `https://raw.githubusercontent.com/ArturMorgen/D-D_Homebrew/master/race-apeling.xml`

and the content file on the last line you'll need to use 
`</elements>` instead of `</element>`

**Comment by NickVendel** [comment]
Yes, i did downloaded index with that link and it gave me error about `</elements>`

**Comment by ArturMorgen** [comment]
I'm trying to change it, but the .index file still has the same problem even though I changed the .xml file so that the last line has </elements> like you said

**Comment by NickVendel** [comment]
It's fine now, you just forgot to update version of the apeling file, which means it wasn't updated. Just delete you folder `best-class` folder and delete .index, then retry downloading it through the app.
Don't forget that after you pushed .xmls you need to change update version every time you make a commit to them, and changing update version of .indexes only when adding new .xml files.
