### ISSUE TITLE
Content Request - Starting Gear and Gold

### ISSUE THREAD

**Issue by assassinmaster46** [aurorabuilder/elements#314]
Hi, this is not a request for anything from an outside source.
I just wanted to see if it were possible to add options for automatically including the starting gear for classes and backgrounds when creating a new character, and possibly also the option for giving the starting gold based on class to purchase gear, all within the rules of the player's handbook.

**Comment by sauxbm** [comment]
I was looking at this today and thought perhaps I was doing something wrong.  Thank you for requesting this.

**Comment by NickVendel** [comment]
it's already been requested. #141 
Also Content Request is for **content**, meaning you want something added to repository, suggestion is for features of the app itself.
