### ISSUE TITLE
Content Request - [All The Lights in the sky Are Stars (ATLAS)]

### ISSUE THREAD

**Issue by ShazaBlasta13** [aurorabuilder/elements#315]
Hello, I just recently got into Aurora builder, and was wondering if the elements from this homebrew add-on my friend showed me could be added to Aurora. I did not make it or had anything to do with its creation, I would just like to see its contents available in Aurora if that is alright. Thank you, and have a nice day.
**Source URL**
A link to the source of the requested content. (website or pdf)
https://www.gmbinder.com/share/-LSNMh6eX2Cm0VdsuZTr
or
https://drive.google.com/open?id=1rklSARxGUyVMHvmFulsOG-CC26Sq9hr4

**Comment by swdriessen** [comment]
Moved request to reddit content repository https://github.com/community-elements/elements-reddit/issues/21
