### ISSUE TITLE
Feat Issue

### ISSUE THREAD

**Issue by LilBig780** [aurorabuilder/elements#320]
I came across a problem where if you take the Magic Initiate Feat and the Ritual Caster Feat, it removes the spells that you choose with previous feat. No matter what order I chose them it did the same thing. Not sure why this is happening, as far as I know there is nothing restricting having these two feats.

**Comment by swdriessen** [comment]
Yep, it's a known issue. I'll be checking out some issues this month, that being one of them.

**Comment by LilBig780** [comment]
Ok good to know thanks

**Comment by NickVendel** [comment]
@swdriessen maybe reopen it, [since it still not fixed](https://www.reddit.com/r/aurorabuilder/comments/civg0e/found_a_bug_related_to_magic_initiate_and_ritual/)

**Comment by LilBig780** [comment]
This is still an issue, I must have accidentally closed it. I apologize if it caused confusion, but please look into fixing this, it hindering me from making character that use both feats.

**Comment by swdriessen** [comment]
Yeah it's fixed for next release. (no ETA)

![featfix](https://user-images.githubusercontent.com/1596388/66661455-56868380-ec47-11e9-815b-3fc99842c577.jpg)

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/977/preview-version-1191216/
