### ISSUE TITLE
New Druid subclass [homebrew]

### ISSUE THREAD

**Issue by Tenpenny77** [aurorabuilder/elements#322]
https://www.dandwiki.com/wiki/Circle_of_the_Claw_(5e_Subclass)

I would love for this subclass to be added to the druid! Please and thank you!

**Comment by NickVendel** [comment]
I did this file [here](https://drive.google.com/open?id=1SSZF_7QhiuKTMy9awtr9R2KvTzMkgz5t), i'll do pull later.

**Comment by Tenpenny77** [comment]
Oh wow, thank you so much!
