### ISSUE TITLE
Enhancement - Custom Backgrounds Rules

### ISSUE THREAD

**Issue by LilBig780** [aurorabuilder/elements#324]
Is it possible to add the Custom Background rules outlined on page 125 of the PHB as well as D&D Beyond, here: https://www.dndbeyond.com/sources/basic-rules/personality-and-background#CustomizingaBackground

**Comment by NickVendel** [comment]
It's not a content request, it's an enhancement of the app. Right now, the only thing you can do i to just create your own background to fit your preferences.
