### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by Ofeck** [aurorabuilder/elements#33]
Hi, I'm new here, I ran Aurora and it's 'too big' for my screen, I've played about with screen res, compatibility options etc and cannot get the program to resize, and thus cannot use the program properly (which is a shame as it looks like it should be great!). I have been using PCs for over 25 years so I reckon I can fix most problems like this but have had no joy with my tinkering and need to ask if this problem can be dealt with. To recap the program runs outsized on my max 1600x1050 monitor which is served by a GeForce 8400GS graphics card. The PC is a Windows 7 build. Thanks in advance!

**Comment by swdriessen** [comment]
I believe the minimum resolution for the current version is 1280*768 but if your display runs at for example 125% scaling it might be too big.

I have reduced the minimum size back as far as the current UI design will let me for the next version which should be out later this month.

Could you attach or email me a screenshot of how it looks when it's too big?

**Comment by swdriessen** [comment]
Give the new version a try.

http://dndbuilder.net/releases#118817

**Comment by Ofeck** [comment]
I will! Thankyou! If it works I'll send you some financial suppprt
