### ISSUE TITLE
issue with importing to kobold fight club

### ISSUE THREAD

**Issue by crockettrockett** [aurorabuilder/elements#331]
They are in XML form, but KFC won't parse them for some reason. any one have luck trying something or having a workaround?

**Comment by NickVendel** [comment]
"Kobold Fight Club is an encounter builder." What are you trying to do with xmls which are content files..?

**Comment by crockettrockett** [comment]
it allows you to import xml files, as shown here https://github.com/Asmor/5e-monsters#adding-your-own-custom-content-to-kobold-fight-club

this allows the input of XML files for monsters, character options, items, etc.

my issue is that the app won't parse these XML files, and I don't know why; it may be due to formatting? but I can't quite understand what the problem is. any help is appreciated 

(app I'm referring to is Fight Club 5e)

**Comment by NickVendel** [comment]
I'm confused, link that you provided talks about google spreadsheets, not about xmls. Either way, they could be structured differently, i doubt standard formatting would do anything, while things like `elements` and tags like `description`, probably just useless there.

**Comment by swdriessen** [comment]
As stated in the email, it's only for Aurora. You'd need to write an application/script to convert the content to the structure used in another app if at all possible.

_Basically; your trying to make a save file for a mario game load in a zelda game. The might look the same, but they aren't made to work on both._

Do you have a link to one of the xml files that the other application uses? That for example adds a race, class, spell, or item?
