### ISSUE TITLE
Githzerhai and the Shield Spell

### ISSUE THREAD

**Issue by Mortisman** [aurorabuilder/elements#332]
In the character builder, when I made a Githzerhai wizard, it does not show me a Shield spell as part of my possible spell list.

I thought that this was because of a Githzerhai's natural ability to cast the Shield spell that's why it is "learned" already. However, that is a racial feature and can only be used once per long rest. Other builders show the Shield spell available for a Githzerhai wizard but I still want to reach out to improve the character builder further

**Comment by NickVendel** [comment]
...i don't understand. You want to have Shield spell not only as Subrace Feature, but also as a Wizard Spell?
Because if this is what you want, i checked, and you can do this. I just created Githzerai and chose Shield as Wizard Spell.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
