### ISSUE TITLE
UA The Artificer Returns - Spell Corrections Needed

### ISSUE THREAD

**Issue by Yohan0625** [aurorabuilder/elements#333]
In the May 2019 Unearthed Arcana the Artificer Returns was published for play-testing.

Unfortunately some of the spells are not listed correctly.

Level 1
Please add Faerie Fire and Feather Fall
Please remove Shield of Faith

Spells available at higher levels should also be reviewed for accuracy.

Thank you.

**Comment by swdriessen** [comment]
Thanks, the list has been updated.
