### ISSUE TITLE
New Class--Dragon Rider

### ISSUE THREAD

**Issue by Tenpenny77** [aurorabuilder/elements#335]
https://drive.google.com/open?id=1ks4-KRT5gJ4ghLfDmmb8MsSSM8ODAhVm

This would be an absolutely amazing class to have! You get to also have a dragon companion! I would love to see this added!

**Comment by swdriessen** [comment]
If it was posted on reddit you can create requests for Reddit in the appropriate repository instead.

https://github.com/community-elements/elements-reddit

Learn More: https://aurorabuilder.com/posts/891/community-driven-content-reddit/
