### ISSUE TITLE
wrong weight being shown with stacked consumables in equipment tab

### ISSUE THREAD

**Issue by 6356h3bgthD** [aurorabuilder/elements#336]
When you have more than one of the same item in the equipment tab in a stack (like ammunition), the weight is calculated as if you had only a single item instead of a stack

**Comment by Kurohimiko** [comment]
Same here. I've tried it with a multitude of items including ammunition, blankets, and items where I added stackability (darts) and the weight doesn't stack.

**Comment by swdriessen** [comment]
Will be fixed in the next release. You can trigger the recalculation by moving an item up and down as a workaround.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/977/preview-version-1191216/
