### ISSUE TITLE
[Issue]: Two-weapon fighting and damage bonus to secondary weapon

### ISSUE THREAD

**Issue by LoZeno** [aurorabuilder/elements#339]
(I'm using version 1.19.308)

When adding a second weapon to use for two-weapon fighting, according to the rules in the PHB, the (light) weapon used for the bonus attack should not add the characteristic's positive bonus to damage unless the character has the Two-Weapons fighting style from the Fighter or Ranger classes; when I use the Equipment screen, though, and I equip a (light) weapon as a off-hand weapon, it does not ignore the characteristic's bonus to damage, and instead always adds it. Also nothing on the character sheet marks the attack as "off-hand". Is this a missing feature or am I simply overlooking something?

**Comment by swdriessen** [comment]
Yes, it's not checking for the feature yet. It's on the _todo_ list.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
