### ISSUE TITLE
KibblesTasty's Artificer

### ISSUE THREAD

**Issue by bunster** [aurorabuilder/elements#340]
https://drive.google.com/file/d/10cV2sROxBUsLixYqnqKPtuDnNGmQ6lVQ/view

Was wondering if now that 2.0 is out it'd be possible to have it added

**Comment by chris-velox** [comment]
I just finished doing this based on the very latest release. You can check it out here: https://github.com/chris-velox/elements-reddit/tree/kibbles-artificer/reddit/reddit-unearthed-arcana/kibbles-artificer
I'll probably do a pull request against the r/UA stuff.
