### ISSUE TITLE
[Issue] Personalised weapons do no automatically get the Proficiency bonus

### ISSUE THREAD

**Issue by LoZeno** [aurorabuilder/elements#342]
Every new custom weapon I create, even though I follow the template for both weapons and proficiencies, does not get the Proficiency bonus when a character equips it.
For example, the following simple weapon:
```xml
<!-- Puchik -->
    <element name="Puchik" type="Weapon" source="Dark Sun 5e Conversion" id="ID_DARKSUN_WEAPON_PUCHIK">
        <supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT</supports>
        <description>
            <p>
                A bone or obsidian punching dagger.
            </p>
        </description>
        <setters>
            <set name="category">Weapons</set>
            <set name="cost" currency="gp">4</set>
            <set name="weight" lb="1">1 lb.</set>
            <set name="slot">onehand</set>
            <set name="damage" type="piercing">1d4</set>
            <set name="proficiency">ID_PROFICIENCY_WEAPON_PROFICIENCY_PUCHIK</set>
        </setters>
    </element>

    <element name="Weapon Proficiency (Puchik)" type="Proficiency" source="Dark Sun 5e Conversion" id="ID_PROFICIENCY_WEAPON_PROFICIENCY_PUCHIK">
        <supports>Weapon, Simple, Melee, ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT</supports>
    </element>
```
When selected by a character with proficiency in Simple Weapons, in the Attacks & Spellcasting section of the character sheet it does NOT include the Proficiency bonus to attack.

Similarly, for the following Martial weapon:
```xml
    <!-- Datchi Club -->
    <element name="Datchi Club" type="Weapon" source="Dark Sun 5e Conversion" id="ID_DARKSUN_WEAPON_DATCHI">
        <supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_PROPERTY_REACH</supports>
        <description>
            <p>
                A datchi club has reach. You can strike opponents 10 feet away with it, but you cannot use it against an adjacent foe. This weapon, generally found in the arenas, is made by affixing a 4‐5 foot length of dried insect hive or roots to a three‐foot long shaft. Teeth, claws, or obsidian shards are embedded into the head of the weapon.
            </p>
        </description>
        <setters>
            <set name="category">Weapons</set>
            <set name="cost" currency="gp">5</set>
            <set name="weight" lb="10">10 lb.</set>
            <set name="slot">twohand</set>
            <set name="damage" type="piercing">1d8</set>
            <set name="proficiency">ID_PROFICIENCY_WEAPON_PROFICIENCY_DATCHI</set>
        </setters>
    </element>

    <element name="Weapon Proficiency (Datchi Club)" type="Proficiency" source="Dark Sun 5e Conversion" id="ID_PROFICIENCY_WEAPON_PROFICIENCY_DATCHI">
        <supports>Weapon, Martial, Melee, ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_PROPERTY_REACH</supports>
    </element>
```
When selected by a Fighter (for example), it does not add the Proficiency bonus to attacks. despite it being a Martial weapon (so, a weapon the Fighter should be proficient with).

Can anyone tell me what am I doing wrong?

**Comment by NickVendel** [comment]
Try including the append line (you can find how i did it with Katana in `custom\third-party\dnd-wiki\items-weapons.xml`).
```xml
	<append id="ID_PROFICIENCY_WEAPON_PROFICIENCY_MARTIAL_MELEE_WEAPONS">
		<rules>
			<grant type="Proficiency" id="ID_PROFICIENCY_WEAPON_PROFICIENCY_DATCHI" />
		</rules>
	</append>
```

**Comment by LoZeno** [comment]
Man, thank you! That was the issue!

Can the `<append>` tag be used for things other than proficiencies? I've been looking for ways to expand or "sligthly alter" existing things (tweak existing classes, like adding the Multiclass element to the Unearthed Arcana's Mystic class), but the only way I have found so far was to copy-paste the element in question and change whatever I needed; if I could use the <append> tag for those things it could be way faster and easier

**Comment by NickVendel** [comment]
Honestly, i'm not sure, i think it doesn't replace anything, it just adds over already existent rules. For example in `custom\homebrew\reddit\arcane-artillery\infra.xml`, at the end, you can find how append used to add proficiency grants to classes.
And in `custom\unearthed-arcana\20190228.xml`, also at the end, you can find append used for extending support of spells. But other than these uses, i don't know if it can be used for something else, i recommend to ask @swdriessen

**Comment by LoZeno** [comment]
Adding proficiency grants to classes is exactly one of the things that I needed, I ended up duplicating the Wizard class only to add Deception in the skill list. Thanks, it's still interesting!

@swdriessen if you have time to explain the capabilities of the `<append>` tag it would be awesome

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
