### ISSUE TITLE
Enthralling Performance DC Issue

### ISSUE THREAD

**Issue by vertigo72** [aurorabuilder/elements#343]
When I generate a character sheet for a College of Glamour Bard, there is an error with DC value in the description:

"...60ft who watched the whole performance, they make a DC==UNKNOWN_VALUE== Wisdom save or are charmed..."

Looking at the file, it appears that {{bard:spell:dc}} is not defined. I think (but could be wrong) it should be {{spellcasting:dc:wis}}.

**Comment by NickVendel** [comment]
{{spellcasting:dc:wis}} is for Wis DC, i'm pretty sure that Bards have Charisma as their spellcasting. But you right, it's wrong stat there.
