### ISSUE TITLE
Content Request - Portable

### ISSUE THREAD

**Issue by ferpectoval** [aurorabuilder/elements#346]
I'm not a coder at all, but would it be too difficult to make this portable?

**Comment by NickVendel** [comment]
This is not a "content request".  
Here's the answer of the developer about mobile version (if that's what you asking about): 
> I don't have the resources to even consider it at this point.

**Comment by ferpectoval** [comment]
> This is not a "content request".
> Here's the answer of the developer about mobile version (if that's what you asking about):

That isn't what I'm asking about, I'm asking if it could be made to allow installation to a removable disc (i.e., usb drive) as opposed to the current state that requires being installed onto a local hard drive. A portable version, not a mobile one.

Apologies if "Content Request" was the wrong heading to comment this under.

**Comment by NickVendel** [comment]
Yeah, i get it now, i just heard how sometimes people call mobile versions a "portable versions". Anyway, i support your request, but i doubt that @swdriessen will prioritize this over actual development process. Maybe after 1.0.

Also, yeah, next time when choosing what issue to create, choose suggestion. Content requests are for repository updates.
