### ISSUE TITLE
Content Request - Sword Mage Class

### ISSUE THREAD

**Issue by Aurocami** [aurorabuilder/elements#350]
https://www.dandwiki.com/wiki/Sword_Mage_(5e_Class)

I'm really interested in this class and I would like to add it to the Aurora Builder but lack the knowledge to do so. If anyone can make this class compatable with Aurora would be nice or tell me how to do it myself would be fine. Thanks in advance.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
