### ISSUE TITLE
Content Request - Tundra Dwarf

### ISSUE THREAD

**Issue by Brink81** [aurorabuilder/elements#351]
**Source URL**
A link to the source of the requested content. (https://www.reddit.com/r/DnD/comments/bg1aja/ochomebrew_dwarven_subraces_revitalize_your/)

[subrace-tundradwarf.txt](https://github.com/aurorabuilder/elements/files/3490538/subrace-tundradwarf.txt)

**Comment by JayPea00101010** [comment]
shouldn't this have been made as a pull request?

**Comment by JayPea00101010** [comment]
https://github.com/community-elements/elements-reddit/pull/14
I've made a request for this (and the other subraces) to be added to the Reddit repo

**Comment by Brink81** [comment]
It probably should have been made as such.  Though this is the first time I
have made such a request so forgive my mistake.  Thank you for adding it.

All the best
