### ISSUE TITLE
Content Request - Dark Arts Player's Companion

### ISSUE THREAD

**Issue by Synderryn** [aurorabuilder/elements#352]
**Source URL**
https://drive.google.com/file/d/1Kr3ZKYy3Me0ZFOhOQAmKBZlB9JUauhW5/view?usp=sharing

**Comment by chris-velox** [comment]
I've actually done this.

**Comment by chris-velox** [comment]
I've done this for myself, but I wasn't sure how to share it out...someone would probably want to review it first.

**Comment by swdriessen** [comment]
leaving a link to the new thread https://github.com/community-elements/elements-reddit/pull/13
