### ISSUE TITLE
Divine Herald cantrips wrong

### ISSUE THREAD

**Issue by Ofeck** [aurorabuilder/elements#353]
The list of cantrips available to the Divine Herald (Rogue subclass) is wrong, it is that of the Sorceror or Wizard (I think) right now. It should be the Cleric cantrip list and the subclass gets to pick _three_ such cantrips at 1st level, at the moment Aurora only allows for chosing two.

![Aurora Error](https://user-images.githubusercontent.com/42326893/63096859-e6b98c80-bf66-11e9-94c2-b8ef64068a60.jpg)

Cantrips gained at later level are also from the wrong list. Other features appear to be working fine.

Oli

**Comment by NickVendel** [comment]
Yup, thanks for noticing, that's easy to fix

**Comment by Ofeck** [comment]
Cool. I was prodding the xml file but hadn't any joy...

**Comment by NickVendel** [comment]
Do you need fix, or did you fixed it yourself? Either way, i'll just [post it here](https://github.com/aurorabuilder/elements/files/3505979/rogue-divine-herald.zip), just put it in _custom_ folder.

**Comment by Ofeck** [comment]
I think I need a fix as my ministrations have had no effect. I could see
what to change, did so, reloaded and it had no effect. Not my specialist
area so someone competent is required!

Thanks for your help!

Oli

**Comment by Ofeck** [comment]
It works! Nice one, thanks again!

Ö

**Comment by NickVendel** [comment]
No problem
