### ISSUE TITLE
Content Request - Demon Character Race

### ISSUE THREAD

**Issue by zukolitos** [aurorabuilder/elements#359]
**Source URL**
A link to the source of the requested content. (website or pdf)
 
i found this link and by no means think this will be made (because it isnt interesting) but i need a demon esc character for a campaign idea, and found one that works and want to know if anyone can make it or help make it (teach me whatever i need) https://www.dandwiki.com/wiki/Demon_Race_(5e_Race)#.3CDemon.3E_Traits is the base that i found that i dont know if it has the entire information needed but thats like 99.999% perfect for what i needed... if someone does this i owe them big time and all my gratitude is sent their way

**Comment by NickVendel** [comment]
It's pretty basic, you can do this yourself, [check my FAQ](https://www.reddit.com/r/aurorabuilder/comments/cn8dyq/unofficial_faq/) for help if you need it.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
