### ISSUE TITLE
Content Request - Ability to make a custom Background as per PHB rules

### ISSUE THREAD

**Issue by QuantumOwl** [aurorabuilder/elements#36]
I would like to request the feature to make a custom background as per the PHB rules, which state that you can pick any two skills and a total of two tool proficiencies or languages and in addition select a feature from any background.

**Comment by swdriessen** [comment]
These are guidelines to create custom backgrounds from scratch or a new one based on an existing.

Tooling to creating elements (items, spells, backgrounds etc) through UI such as these is something i plan to start adding after the release of v1.0 out of preview.
