### ISSUE TITLE
SUGGESTION: Make the equipment tab bigger

### ISSUE THREAD

**Issue by rkr87** [aurorabuilder/elements#362]
The equipment tab on the front page of the character sheet doesn't display enough items. Would it be possible to make it bigger? Either by;

 - reducing the height of the AC, HP & Speed, Senses & conditions tabs.

or

- having two columns in the equipment tab for items - more horizontal space could be gained by removing the leftmost quantity column as item quantities are displayed twice currently, eg, 10 Torch (10).

Thanks,

**Comment by swdriessen** [comment]
The next version will have a dedicated equipment page.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/977/preview-version-1191216/
