### ISSUE TITLE
Content Request - Lycanthrope (Weretiger)

### ISSUE THREAD

**Issue by RiShKiNz** [aurorabuilder/elements#363]
Hi. I was interested in Lycanthropy, specifically Weretiger as I want to base a character on it.

The information is on pages 208 & 211 in the Monster Manual. The following link has the same information, although it doesn’t have the information on gaining a Str of 17 once receiving lycanthropy & the hybrid/tiger form being of large size.

http://www.5esrd.com/gamemastering/monsters-foes/monsters-by-type/humanoids/lycanthropes/lycanthrope-weretiger/

 Thank you :)

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
