### ISSUE TITLE
Save PDF always generates Form-Fillable PDF for specific character

### ISSUE THREAD

**Issue by rkr87** [aurorabuilder/elements#373]
I have several characters I've created through Aurora and all of them work perfectly fine, aside from one, which no matter what I try always generates a form-fillable PDF regardless of the options I've selected in the "Character Sheet Settings".

I've tried, turning all card pages off, creating a new character with the same setup, copying the contents of the character's xml (dnd5e) file into a copy of a known working character's xml.

I've attached the character file in question.

Thanks for the awesome program, for the time being I'm working around the issue by printing the generated PDF to a PDF file again, though some quality is lost with this method.
[Raji.zip](https://github.com/aurorabuilder/elements/files/3632711/Raji.zip)

**Comment by NickVendel** [comment]
@rkr87 [is this what you wanted?](https://github.com/aurorabuilder/elements/files/3747515/raji.pdf)

**Comment by rkr87** [comment]
@NickVendel it is indeed, how did you get it to generate without form-fillable fields?

Thabks.

**Comment by NickVendel** [comment]
i just unchecked form-fillable in settings, i honestly don't know why this character doesn't want to do the same for you.

**Comment by rkr87** [comment]
Strange, I'll try a reinstall of Aurora when I'm next at the computer and see if that fixes it for me.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
