### ISSUE TITLE
Content Request - Religion Images

### ISSUE THREAD

**Issue by Majnara** [aurorabuilder/elements#374]
**Additional context**
I will admit that I did not look over all of the suggestions, so somebody may have already added this. There is a list in the back of the PHB with the main deities from the different realms. Would it be possible to get images of these added for use in the allies screen?

**Comment by swdriessen** [comment]
If you have a collection of images (same size, same style etc) i might consider including them in the software as presets.

**Comment by Majnara** [comment]
I am currently working on that for my group. Once I have it completed I will let you know.
