### ISSUE TITLE
Content Request - Xanathar's Lost Notes to Everything Else

### ISSUE THREAD

**Issue by acelegna** [aurorabuilder/elements#377]
_removed link to pdf_

This would be a big project, but has lots of incredible content worthy of the sequel to Xanathar's Guide to Everything

**Comment by swdriessen** [comment]
include the third-party index to get this content

https://github.com/aurorabuilder/elements/tree/master/third-party/dms-guild/xanathars-lost-notes-to-everything-else

create a new issue if anything is missing
