### ISSUE TITLE
Oath of Avarice not pulling from The Compendium of Forgotten Secrets

### ISSUE THREAD

**Issue by ferpectoval** [aurorabuilder/elements#378]
When making a Paladin the Oath of Avarice (Sacred Oath available from the Currency Conspiracy portion of The Compendium of Forgotten Secrets) is not an option despite the Compendium being loaded as a source and other options (e.g., Ashen Lineage for a Sorcerer) being available.

**Comment by ferpectoval** [comment]
I found the XML file in the Compendium tracker post:
https://github.com/aurorabuilder/elements/issues/249#issuecomment-515654621

so the Index file hasn't been updated but it's an easy fix client-side, though I don't know if updating the source files will remove that.

**Comment by swdriessen** [comment]
It's not included yet, it will be once it's checked and tested.
