### ISSUE TITLE
Error in the PHB sailor background line 46

### ISSUE THREAD

**Issue by QuantumOwl** [aurorabuilder/elements#38]
should be separated in 2 different lines like this

`<item id="6">I never pass up a friendly wager.</item>`
`<item id="7">My language is as foul as an otyugh nest.</item>` 

https://github.com/aurorabuilder/elements/blob/master/core/players-handbook/backgrounds/background-sailer.xml

**Comment by swdriessen** [comment]
Thanks, fixed.
