### ISSUE TITLE
Content Request - Magical Girl (Homebrew class)

### ISSUE THREAD

**Issue by dillnex30** [aurorabuilder/elements#382]
[magical girl.pdf](https://github.com/aurorabuilder/elements/files/3704468/magical.girl.pdf)
If you don't mind helping, that is.

**Comment by dillnex30** [comment]
I have no idea how to pull requests, so I'll just drop this here and hope that someone sees it. I got some help with creating the class, and after long, tedious hours of combing the internet and other classes, we finally finished the class. Can someone point me towards where I submit it?

**Comment by swdriessen** [comment]
Assuming this was posted on reddit (i don't see a source, just a reddit username) you can submit it to https://github.com/community-elements/elements-reddit

This is part of the recent [restructuring](https://aurorabuilder.com/posts/891/community-driven-content-reddit/) where homebrew content from for example reddit will be located so it can be maintained by the community directly.
