### ISSUE TITLE
Content Request - Awakened Bear player race!

### ISSUE THREAD

**Issue by mh1981** [aurorabuilder/elements#385]
My dudes, I am jacking up my XML trying to create it, myself, but I'm looking for a playable and balanced Awakened Bear race for Aurora Builder.

If you want to go all-out and sub-race black, brown, polar, grizzly, whatever, I'd love it and I'm sure others would, too.  Other Awakened animals, even plants, would be rad.

Thanks in advance, I know some other nutter with more skills than me will be down to do this.

**Comment by JayPea00101010** [comment]
https://cdn.discordapp.com/attachments/430618173587324939/436998787131506688/unknown.png
this one?

**Comment by JayPea00101010** [comment]
if not could you leave a link to the one you mean

**Comment by mh1981** [comment]
> https://cdn.discordapp.com/attachments/430618173587324939/436998787131506688/unknown.png
> this one?

Looks good to me!  I kinda feel it should have a proficiency ribbon, maybe Survival?  Either way, looks perfect.

**Comment by JayPea00101010** [comment]
that should be easy to make on your own, ask on the discord if you need any help

**Comment by swdriessen** [comment]
Not the place to put together homebrew content. If you have an actual request you can request it in the appropriate repository and provide a source (url) to the website where it can be found.

**Comment by JayPea00101010** [comment]
https://github.com/community-elements/elements-dndwiki
https://github.com/community-elements/elements-reddit

links to the DnDWiki and Reddit repos, if you're going to remake the request could you provide a source URL for the one you want and make a reqest to the appropriate repository (like swd said)
