### ISSUE TITLE
Question - Is there any way to make this tool web-based?

### ISSUE THREAD

**Issue by QuantumOwl** [aurorabuilder/elements#39]
I use different computers and mobile devices but I'm always theorycrafting new builds or improvement to current ones and would like to know if there is any way to have it on all of my devices on the go.

**Comment by swdriessen** [comment]
It's a local (& offline) Windows application, so short answer; _no_.

You could change (in settings) the 'characters' folder that holds your characters/custom files/portraits to a folder in onedrive/gdrive/dropbox so it syncs to your computers.

I have some plans for future things but nothing in the near future.
