### ISSUE TITLE
Content Request - Warforged subclasses

### ISSUE THREAD

**Issue by AlukardSins** [aurorabuilder/elements#396]
https://www.dndbeyond.com/races/warforged
Subraces and armor types, not just 'composite armor'.

**Comment by Azzzzzy** [comment]
Are you sure you're picking the right warforged subrace? There's currently 2 in the builder and to get the one you are talking about you need to have the third-party.index downloaded.

![image](https://user-images.githubusercontent.com/41882065/67632608-3f60ac00-f86b-11e9-82a9-738aa6f9aa95.png)
The one you're referring to is the Wayfinder's Guide to Eberron which does have the sub-races and armor.
![image](https://user-images.githubusercontent.com/41882065/67632625-759e2b80-f86b-11e9-9c58-57e378b0a06c.png)

**Comment by AlukardSins** [comment]
Yep, found it, wasnt using third party libs beacuase the DM said so, but i managed to convince otherwise.
