### ISSUE TITLE
Aetherborn Names

### ISSUE THREAD

**Issue by swdriessen** [aurorabuilder/elements#4]
I'm not familiar with Plane Shift lore. Would be nice if anyone has some aetherborn names to replace these with. 

https://github.com/aurorabuilder/elements/blob/465559ff785d045c840d0e9647d3e33fb3cbe7fa/unearthed-arcana/planeshift/kaladesh/race-aetherborn.xml#L34-L36

**Comment by chrisjfoss** [comment]
Aetherborn are genderless, if I'm not mistaken.  A couple examples from mtg are : Yahenni, Rajul, Ranbir, and Gonti - found from [here](https://mtg.gamepedia.com/List_of_secondary_characters/Kaladesh).  Alternatively, this [homebrew](http://homebrewery.naturalcrit.com/print/Hkbr8EF9Sl?dialog=true) has a list of names you could use.
