### ISSUE TITLE
Content Request - [5e-Battle Medic]

### ISSUE THREAD

**Issue by Rcktrouble** [aurorabuilder/elements#406]
**Source URL**
https://www.dandwiki.com/wiki/Battle_Medic_(5e_Class)

Thank You.

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/

https://github.com/community-elements/elements-dndwiki/issues/11

**Comment by Rcktrouble** [comment]
Probably user error on my end, but I can't find anything with Combat Medic
in the files.

**Comment by swdriessen** [comment]
It's not added, the request has been moved to the new wiki repository as part of the restructuring of some homebrew sources. See links.
