### ISSUE TITLE
Content Request - Elemental Evil Player's Companion

### ISSUE THREAD

**Issue by NLZ** [aurorabuilder/elements#408]
https://thetrove.net/Books/Dungeons%20&%20Dragons/D&D%205th%20Edition/Modules/Elemental%20Evil%20Players%20Companion.pdf

Small complementum for Princes of the Apocalypse with new races and spells.

**Comment by swdriessen** [comment]
You'll find the content when you add the supplements (also include the core).

https://aurorabuilder.com/content/#repository

**Comment by NLZ** [comment]
You are right, almost everything but the Deep Gnome subrace is implemented, which I was looking for. Goliath is also missing from princes-of-the-apocalypse, but instead included from volo, so no need to bother with that.

I could try to implement the Deep Gnome.

Btw  here is the legal link: https://media.wizards.com/2015/downloads/dnd/EE_PlayersCompanion.pdf

**Comment by swdriessen** [comment]
It's implemented as 'svirfneblin' from Sword Coast Adventurer’s Guide.

**Comment by NLZ** [comment]
Ahh, I see. Why not call them Deep Gnomes in Aurora? Even Sword Coast Adventurer’s Guide primarily refers to them as Deep Gnomes.

**Comment by swdriessen** [comment]
All those files i added were from my private files, some might have slipped through how i used them when generating characters. Might update it as part of my files cleanup in the future.
