### ISSUE TITLE
Favored Enemy alternative

### ISSUE THREAD

**Issue by Cyga319** [aurorabuilder/elements#41]
In the PHB, it's stated that instead of choosing from the list of foes provided, players could instead choose two races of humanoid like gnolls and orcs. Is there a way to pull this off in the editor, or is this not implemented yet?

**Comment by Darkharlequin** [comment]
I also cannot find the humanoids listing for a favored enemy for the ranger class. I just got aurora a couple of weeks ago and have downloaded everything I was able to find or so I thought, am I missing something or is this still unavailable

**Comment by swdriessen** [comment]
Added in #412
