### ISSUE TITLE
Features overflow

### ISSUE THREAD

**Issue by bunster** [aurorabuilder/elements#410]
I've noticed that on multiclass characters, the character sheet will overflow info in the features box and not put it anywhere else.

Example of what I mean: https://i.imgur.com/symGsyw.png

**Comment by swdriessen** [comment]
Sometimes depending on the descriptions it can't 100% calculate the required space and the fontsize is slightly too big which makes it cut off. In the future when the font size drops below a certain point i will generate a page with more space for the features.

For now you can generate a form fillable sheet with disabled formatting for the characters that have too much text. Then you can edit content and the font size in adobe reader for example.
