### ISSUE TITLE
Incorrect Spell Level

### ISSUE THREAD

**Issue by Sett-Resu** [aurorabuilder/elements#415]
The Spell Conflagrate is incorrectly listed as a Cantrip instead of a 3rd-level Spell

_Grimlore's Grimoire_

**Comment by Azzzzzy** [comment]
Are you sure?
![image](https://user-images.githubusercontent.com/41882065/69026587-b976e300-0988-11ea-9fb2-76af35de15be.png)

**Comment by swdriessen** [comment]
Assuming the current version you can download it's correct. An older version (even though it's in color) had a 3rd-level spell called 'Conflagration'.
