### ISSUE TITLE
Kalashtar's Psychic Glamour - should give ADVANTAGE, not PROFICIENCY [Wayfinder's Guide to Eberron]

### ISSUE THREAD

**Issue by LoZeno** [aurorabuilder/elements#417]
**Describe the issue**
The Kalashtar's race as described in the Wayfinder's Guide to Eberron, has a racial trait called Psychic Glamour, with the following description:
```
Choose one of the following skills; Insight, Intimidation, Performance, or Persuasion. You have advantage on all ability checks you make with that skill.
```

The way it is implemented now, though, it adds one of the three skills as a Proficiency instead, which prevents (for example) a bard from selecting the Performance skill with this trait and get the proficiency bonus AND the advantage when rolling.

**Comment by swdriessen** [comment]
Thanks, should be fixed!
