### ISSUE TITLE
Recommendation - Have the associated ability in parentheses beside the skill

### ISSUE THREAD

**Issue by QuantumOwl** [aurorabuilder/elements#42]
Basically, this is a QoL thing more than anything. This would enable people that have lopsided stats (15,8,15,8,8,15 for example) to choose their skills more efficiently.

Example Attached
<img width="618" alt="cbbbture" src="https://user-images.githubusercontent.com/16347992/44825901-aab4dc80-abda-11e8-8935-29649baccfae.PNG">

**Comment by swdriessen** [comment]
I'll think about adding some kind of optional hints like this for elements.

The description should provide this information at the moment.

> Make a **Dexterity** (Stealth) check when you attempt to conceal yourself from enemies, slink past guards, slip away without being noticed, or sneak up on someone without being seen or heard.
