### ISSUE TITLE
Content Request: Homebrew Race, Wolfkind

### ISSUE THREAD

**Issue by Banewolf1291** [aurorabuilder/elements#425]
**Source URL** https://www.dandwiki.com/wiki/Wolfkind_(5e_Race)
A link to the website where the requested content is publicly available.

**Comment by swdriessen** [comment]
You can create requests for D&D Wiki in the appropriate repository instead.

https://github.com/community-elements/elements-dndwiki

Learn More: https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
