### ISSUE TITLE
Content Request - Odyssey of the dragonlords - Modiphius publishing

### ISSUE THREAD

**Issue by CthulhuBits** [aurorabuilder/elements#431]
Just a request for a odyssey of the dragonlords index file for aurora if anyone can. Thank you.

**Comment by JayPea00101010** [comment]
> https://www.modiphius.net/collections/odyssey-of-the-dragonlords/products/odyssey-of-the-dragonlords-players-guide-free
for coding purposes

Looks interesting, I might do it

**Comment by swdriessen** [comment]
I saw someone (not sure who) was working on this a while back in the discord server. Not sure if it was 1 archetype or all content.

**Comment by JayPea00101010** [comment]
ah, no point in making it if someone else has already made a start, I've learnt that the hard way XD

**Comment by swdriessen** [comment]
content from the player's guide has been merged in #442
