### ISSUE TITLE
Error in Aarakocra Language 'Auran'

### ISSUE THREAD

**Issue by Lucan11** [aurorabuilder/elements#434]
**Describe the issue**
See the attached pictures for a step-by-step visual reproduction.

When selecting the Aarakocra race, you get prompted by an error saying: 'Unable to find ID_MM_LANGUAGE_AURAN of type language that was set as grant in Aarakocra (Race)'.

This error will pop-up a couple of times, but can be dismissed by clicking 'OK', the race is then selected and functions properly. However, every further selection affecting the character (saving, loading, selecting feats, class, equipment... etc) will trigger this prompt. Loading the saved character will trigger this error A LOT.

**Additional context**
I tried checking for this language definition in my core files and found it defined in core/monster-manual/languages.xml and used in supplements/princes-of-the-apocalypse/races/race-aarakocra.xml.

So I'm not sure where the error originates from precisely. I hope this is sufficient information for you to fix the problem.

![1](https://user-images.githubusercontent.com/17274479/70896839-c6234100-1ff1-11ea-90f2-d1da3de0ef75.png)
![2](https://user-images.githubusercontent.com/17274479/70896841-c6234100-1ff1-11ea-869f-060c592971d5.png)
![3](https://user-images.githubusercontent.com/17274479/70896842-c6234100-1ff1-11ea-9b00-c2727d58ab28.png)
![4](https://user-images.githubusercontent.com/17274479/70896843-c6234100-1ff1-11ea-82aa-7d449e543c29.png)
![5](https://user-images.githubusercontent.com/17274479/70896846-c6234100-1ff1-11ea-9443-ca3b83b5602c.png)

**Comment by JayPea00101010** [comment]
You need to download core.index
the SRD doesn't include everything from there

**Comment by JayPea00101010** [comment]
![image](https://user-images.githubusercontent.com/49499816/70899508-a63e4e00-1fee-11ea-9a04-04e7a98910e7.png)
![image](https://user-images.githubusercontent.com/49499816/70899624-e7366280-1fee-11ea-8bbf-452c6f0752dc.png)
see the different sources

**Comment by Lucan11** [comment]
Yep that was it, thanks! I figured that the core was automatically included, but that's not the case...

**Comment by JayPea00101010** [comment]
you're not the only person who's assumed that, dw
