### ISSUE TITLE
Addition to revised ranger

### ISSUE THREAD

**Issue by omerbl1996** [aurorabuilder/elements#436]
https://media.wizards.com/2016/dnd/downloads/2017_01_UA_RangerRogue_0117JCMM.pdf

I wanna try to make a revised ranger but with the Horizon Walker Archetype. If someone can either send me a proper xml file or create one I'd really appreciate it!!

**Comment by swdriessen** [comment]
You can subscribe to notification to the pull request to know when it has updates: https://github.com/aurorabuilder/elements/pull/118

If you grabed the file manually you can homebrew (_note: it's not supported_) the horizon walker and append the archetype support to it:
```
<append id="ID_WOTC_XGTE_ARCHETYPE_HORIZON_WALKER">
	<supports>Ranger Conclave</supports>
</append>
```
You can put this append in the revised ranger file for example.

**Comment by omerbl1996** [comment]
I've never done this thing haha. I have the file itself but I don't know where to put it exactly. If you can tell me how and where I'll be able to go on from there myself

נשלח מהאפליקציה 'דואר' עבור Windows 10

מאת: Bas Driessen
נשלח: יום חמישי 16 ינואר 2020 13:26
אל: aurorabuilder/elements
עותק: omerbl1996; Author
נושא: Re: [aurorabuilder/elements] Addition to revised ranger (#436)

You can subscribe to notification to the pull request to know when it has updates: #118
If you grabed the file manually you can homebrew (note: it's not supported) the horizon walker and append the archetype support to it:
<append id="ID_WOTC_XGTE_ARCHETYPE_HORIZON_WALKER">
	<supports>Ranger Conclave</supports>
</append>
You can put this append in the revised ranger file for example.

**Comment by omerbl1996** [comment]
It doesn't work for me. Can you please do me a favor and add the lines you
said in the file and send it to me? you don't have to if it's too much of a
bother. What happens is I'm trying to open a new character in the aurora
and when I try to find the Horizon Walker in the ranger conclaves It
doesn't show.

‫בתאריך יום ה׳, 16 בינו׳ 2020 ב-13:49 מאת ‪Bas Driessen‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by swdriessen** [comment]
unzip the file in your `custom\user` folder, this should work (untested i don't have the revised ranger as a file around)
[additional-conclaves.zip](https://github.com/aurorabuilder/elements/files/4073222/additional-conclaves.zip)
