### ISSUE TITLE
Xanathar's Guide to Everything

### ISSUE THREAD

**Issue by Slepnair** [aurorabuilder/elements#437]
https://drive.google.com/file/d/1gw-1Rh7i4RhrUnsL57kOrPyJNNoykkXG/view?usp=sharing

I am specifically after the Warlock Otherworldly Patrons. There are a number of things in the book that are good and can be added as well.

**Comment by swdriessen** [comment]
It's included in the supplements: https://aurorabuilder.com/content/#repository
