### ISSUE TITLE
Page and source book references

### ISSUE THREAD

**Issue by portdan** [aurorabuilder/elements#444]
Hello,

I did not find an option to show the page and source book reference next to a spell/feature/item/etc...
I think some elements of the character sheet can use this, for example the 'Features & Traits' could use this option to minimize the amount of text.

**Comment by swdriessen** [comment]
Pages for source books are currently not implemented and the source book reference is only available on for example the spell cards (and other cards) when used.

It's been on my list a while but will not be added in the near future.
