### ISSUE TITLE
The Weaveshaper

### ISSUE THREAD

**Issue by omerbl1996** [aurorabuilder/elements#452]
If you could add the Weaveshaper class it seems amazing and I'd like to try it!!
[Genuine - NEW Weaveshaper Rewoven v1.pdf](https://github.com/aurorabuilder/elements/files/4069725/Genuine.-.NEW.Weaveshaper.Rewoven.v1.pdf)

**Comment by swdriessen** [comment]
Please also provide a url to the page where to find the PDF for future updates.

**Comment by omerbl1996** [comment]
https://drive.google.com/open?id=1btlMlloqviizqzb4hjielJ3AP1HYTQEP
https://drive.google.com/open?id=16Vpd9bP3t2IKm79w7rnB2yP5e7vhnhxH

Hope these will suffice. You have here 2 options. One's older but I think players will enjoy both options.

**Comment by swdriessen** [comment]
Thanks, but i meant a url to the website of the author that links to the PDFs.

**Comment by omerbl1996** [comment]
I'm not sure whether there will be an update to this class since it's not
mine. It belongs to the author of the Compendium of Forgotten Secrets.
בתאריך יום ה׳, 16 בינו׳ 2020, 12:44, מאת Bas Driessen ‏<
notifications@github.com>:

**Comment by omerbl1996** [comment]
https://www.genfantasypress.com/

Will this suffice?

‫בתאריך יום ה׳, 16 בינו׳ 2020 ב-12:59 מאת ‪Omer Barlev‬‏ <‪
omerbl1996@gmail.com‬‏>:‬

**Comment by swdriessen** [comment]
Yeah, found it, i assumed it was new since it said NEW and v1 and didn't include multiclassing rules. 

https://www.genfantasypress.com/post/cofs-a-release-anniversary-the-weaveshaper-rewoven

**Comment by omerbl1996** [comment]
Ok cool. Hope people wil love it! Also I asked a month ago whether id the
horizon walker can be added as a conclave for the revised ranger. Is it
possible?

בתאריך יום ה׳, 16 בינו׳ 2020, 13:13, מאת Bas Driessen ‏<
notifications@github.com>:

**Comment by swdriessen** [comment]
I'll leave a note in https://github.com/aurorabuilder/elements/issues/436

**Comment by swdriessen** [comment]
It's included, feel free to test it.
