### ISSUE TITLE
Ranger Companion Option Empty

### ISSUE THREAD

**Issue by InsanityAtHeart** [aurorabuilder/elements#46]
Hey there Aurora team! Just wanted to post this issue as it confused me and thought it might be something that's easily fixed.

I was going along, designing how I want my character to be, I made a rogue 6/warlock 4/ranger 3, however, when I reached ranger 3 and chose the Beast Master archetype, the Ranger Companion option showed up, but it was empty, there were no choices listed at all.

I've added all the additional content so there shouldn't be any missing files. I'm not sure whether it's due to my class choices or multiclassing in general or maybe it just won't let me due to having so much in my Traits box already, but it's an issue I thought I'd bring up nonetheless.

**Comment by swdriessen** [comment]
The companions have not been implemented yet, it's something i'm planning to work on in the next few weeks when i can find the time. It should come with a dedicated spot on the sheet for a companion.

**Comment by swdriessen** [comment]
Initial version of companions has been added in the new version.
