### ISSUE TITLE
Content Request [The Gentleman from DnD Wiki]

### ISSUE THREAD

**Issue by Broadsword700** [aurorabuilder/elements#461]
#https://www.dandwiki.com/wiki/The_Gentlemen_(5e_Class)

**Comment by swdriessen** [comment]
You can create requests for D&D Wiki in the appropriate repository instead.

https://github.com/community-elements/elements-dndwiki

Learn More: https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
