### ISSUE TITLE
Unable to find ID_WOTC_PHB_LANGUAGE_THIEVES_CANT

### ISSUE THREAD

**Issue by jelmnainen** [aurorabuilder/elements#462]
**Describe the issue**
When I create a new character, go to class-tab and choose Rogue, I'm hit with "Unable to find ID_WOTC_PHB_LANGUAGE_THIEVES_CANT of type Language that was set as grant in Thieve's Cant (Class Feature)"

**Additional context**
I have a fresh install of Aurora 1.19.1216, downloaded the additional content from https://raw.githubusercontent.com/aurorabuilder/elements/master/supplements.index.

**Comment by swdriessen** [comment]
Be sure to also include the core index which contains the full content from the core rulebooks:
`https://raw.githubusercontent.com/aurorabuilder/elements/master/core.index`

**Comment by jelmnainen** [comment]
Sorry! Mistook "required content" as "ships with this". Thanks for the understanding reply.

**Comment by swdriessen** [comment]
No worries!
