### ISSUE TITLE
content request wild mage sub class 

### ISSUE THREAD

**Issue by justabuckII** [aurorabuilder/elements#472]
**Source URL**
A link to the website where the requested content is publicly available.
a wild mage subclass for the sorcerer class

**Comment by swdriessen** [comment]
If you meant the _Wild Magic_ origin from the player's handbook, follow the steps to include additional content on the website.

https://aurorabuilder.com/content/#repository

If you meant another sorcerous origin, create a new request following these [guidelines](https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md#content-requests).
