### ISSUE TITLE
Racial Spells and Known Spells

### ISSUE THREAD

**Issue by vertigo72** [aurorabuilder/elements#473]
When I choose a race that has the ability to cast a spell as a racial feature, I am unable to have that character learn that spell. For example:

Level 5 Tiefling Warlock - I cannot select hellish rebuke or darkness to learn as a warlock spell.

My understanding is that the Tiefling can cast both spells once per long rest, but does not learn or know the spells for the purpose of casting with a spell slot.

**Comment by swdriessen** [comment]
Yes, this is something i have to do a rewrite of the builder for as it's not ~~easy~~ possible to change how it works internally.

I tend to not include these grants in new content, but some content still has this. While still valid, it can sometimes cause a conflict when you also want those spells from your spellcaster.

What you can do is go to the equipment and add these spells to the warlock list of known spells by adding them from the 'Additional Warlock Spells' and leave the selection where you wanted to select the spell blank (you can remove a selected spell by pressing delete when highlighting a selection) .

Or you can override the element that gives these spells with a custom version that doesn't give these spells.

save this example as `homebrew-tiefling.xml` (name can be anything) to your `custom\user` folder: 
```xml
<?xml version="1.0" encoding="utf-8" ?>
<elements>

    <element name="Infernal Legacy" type="Racial Trait" source="Player’s Handbook" id="ID_RACIAL_TRAIT_INFERNAL_LEGACY">
        <description>
            <p>You know the thaumaturgy cantrip. Once you reach 3rd level, you can cast the hellish rebuke spell once per day as a 2nd-level spell. Once you reach 5th level, you can also cast the darkness spell once per day. Charisma is your spellcasting ability for these spells.</p>
        </description>
        <sheet>
            <description>You know the thaumaturgy cantrip. Charisma is your spellcasting ability for these spells.</description>
            <description level="3">You know the thaumaturgy cantrip. You can cast the hellish rebuke spell once per day as a 2nd-level spell. Charisma is your spellcasting ability for these spells.</description>
            <description level="5">You know the thaumaturgy cantrip. You can cast the hellish rebuke spell once per day as a 2nd-level spell. You can also cast the darkness spell once per day. Charisma is your spellcasting ability for these spells.</description>
        </sheet>
    </element>
    
</elements>
```
(this has the rules that grant the spells removed and will override the existing one)

**Comment by vertigo72** [comment]
Thank you. Your suggestions are a great help.

Another workaround I was going to try was to duplicate the darkness and hellish rebuke spells in an xml file, but add "_RACIAL" to their ID. Then I can override the Infernal Legacy racial trait to grant the *_RACIAL spells. This is a little ugly, but I assume will it will fix the issue as well.

**Comment by swdriessen** [comment]
A little more work, but yes as long as the ID is different that would work. You can remove the supports from those 'homebrew' spells to avoid having them show up in selections for the spellcasters on other characters as they are not needed for that.

You can also add a `<compendium display="false" />` to the element to have it hidden from compendium searches since it's a duplicate.
