### ISSUE TITLE
Is there anyway to add the lycanthropy rules for players?

### ISSUE THREAD

**Issue by J75057exe** [aurorabuilder/elements#475]
As far as I can gather there's no way to add the ware-creature rules to a PC. I think this could probably be done in a similar way to feats but I lack the brainpower to add that myself. 
In terms of content specifics, I'm talking about the rules outlined in the Monster Manual and Curse of Strahd. If you're adding player variations, I suggest adding the vampire and vampire spawn rules at the same time.
tyvm,
A

**Comment by swdriessen** [comment]
It's not implemented, you can take a look at this if it's usable for you: https://github.com/aurorabuilder/elements/pull/391/files

_note; it uses a character option to toggle it on/off_
