### ISSUE TITLE
Some additions for overall diversity

### ISSUE THREAD

**Issue by omerbl1996** [aurorabuilder/elements#476]
https://www.genfantasypress.com/blog

Just saw this blog with many new subclasses and thought it'll be a cool addition and he has some good takes on different archetypes for each class

**Comment by swdriessen** [comment]
When these get bundled and released into a compendium they can be considered for inclusion into the repository. Currently this is just third-party playtest material which is out of the [project scope](https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md#project-scope).
