### ISSUE TITLE
Artificer Armorer: Armor Modifications bug?

### ISSUE THREAD

**Issue by CBulldog09** [aurorabuilder/elements#478]
I noticed the Armor Modifications feature of the Artificer's Armorer subclass (UA file 20200224.xml), doesn't automatically add the +2 attunement limit to the character. If that's intentional, feel free to mark this as closed/solved or delete it. If it's not, I fixed the issue with a couple lines of code.

`<stat` name="attunement:max" value="6" bonus="base" level="10" />
`<stat` name="attunement:max" value="7" bonus="base" level="14" />
`<stat` name="attunement:max" value="8" bonus="base" level="18" />

I kept the total number of infusions in line with the number granted by the Magic Item Adept/Savant/Master.

Sorry in advance if this isn't the place for this or this was intentionally omitted.

**Comment by swdriessen** [comment]
The feature only increases the number of infusions, it doesn't allow you to attune to additional items.
The amount of infusions is updated to 7 in the sheet description of the Infuse Item feature.

It's the right place to report any issues, thanks.

**Comment by CBulldog09** [comment]
You're right. I got tripped up by the wording and assumed total infused items also increased number attuned. In that case, does the total amount of infused items increase to 5 at level 9, 6 at level 10, 7 at level 14, and 8 at level 18?

**Comment by swdriessen** [comment]
Oh yeah, I used a bad example (context: i used a 15th-level Artificer as example), it increases by 2 as soon as you get the feature.

![image](https://user-images.githubusercontent.com/1596388/75630274-8aa81400-5be9-11ea-8c2a-ef983efdfc58.png)

This number changes to reflect the total amount (3+2) as soon as you are level 9.

**Comment by CBulldog09** [comment]
Oh gotcha. Thanks for clearing that up.
