### ISSUE TITLE
Class Feature Variants Unearthed Arcana

### ISSUE THREAD

**Issue by CBulldog09** [aurorabuilder/elements#479]
I noticed that the above [UA](https://media.wizards.com/2019/dnd/downloads/UA-ClassFeatures.pdf), on both the [XML](https://raw.githubusercontent.com/aurorabuilder/elements/master/unearthed-arcana/2019/20191104.xml) file and the [Github](https://github.com/aurorabuilder/elements/blob/master/unearthed-arcana/2019/20191104.xml) file, doesn't have any of the code elements. Is there an updated version of the file anywhere that actually has the code? Will the content be included at a later date?

I'm sorry if this has been asked before. I checked the subreddit and github but didn't see any posts about this specific UA.

**Comment by swdriessen** [comment]
It has an indicator on the listed source:

![image](https://user-images.githubusercontent.com/1596388/75748067-e88a4800-5d1e-11ea-9b79-352f0303ce7b.png)

(and there was a note in the UA post after this one: https://aurorabuilder.com/posts/946/unearthed-arcana-fighter-rogue-and-wizard/ )

The variant features are currently not supported and require significant code changes to properly implement. If they ever get introduced in an official release it will be looked at again. You can customize files to emulate it but it will require changes in many places.

There is a custom file on the discord #unearthed-arcana channel that might work for you.

**Comment by CBulldog09** [comment]
I saw the indicator, and had a feeling that would be the case, since it's such an extensive amount of changes. I just wanted to make sure, and that I wasn't missing something.
Thanks.
