### ISSUE TITLE
Unearthed Arcana: Subclasses, Part 3 Ariticer (Armorer) speed issue

### ISSUE THREAD

**Issue by acelegna** [aurorabuilder/elements#486]
First of all, great work with this!!!

I did encounter an issue with one of the abilities:

I was building a 9th level Artificer (Armorer subclass) Human (Speed 30 ft) and choosing a Plate (Heavy Armor) as his Infiltrator Power Armor. (+5 ft because of Powered Steps)

Heavy Armor in the PHB says:
"Heavier armor interferes with the wearer’s ability to move quickly, stealthily, and freely. If the Armor table shows “Str 13” or “Str 15” in the Strength column for an armor type, the armor reduces the wearer’s speed by 10 feet unless the wearer has a Strength score equal to or higher than the listed score."

The Power Armor feature says:
"If the armor normally has a Strength requirement, the power armor lacks this requirement for you."

Therefore, when equipping a Infiltrator Power Armor, my speed should be 35 and not 25 as it is generated.

**Comment by swdriessen** [comment]
Thanks.

This is a current limitation which makes it a bit tricky. What you can do is create a custom (temporary) item that increases the speed again by 10 to have it show up correct, or edit it on the sheet.

**Comment by acelegna** [comment]
Thank you for the reply! I did some prodding and ended up editing the .xml file to make power steps 15 in stead of 5 to make up for the difference ;)

**Comment by NickVendel** [comment]
as we with user Rieleniel#4413 (on Discord) find out, we can fix this issue with granting this stat from Power Armor feature:
```xml
<stat name="speed" value="0" bonus="armor" requirements="![str:15]" />
```
this would negate -10 to speed when wearing any heavy armor and not having needed Strength for it. I did test it and it seems to work fine for every heavy armor i checked.

**Comment by NickVendel** [comment]
Separately i would like to add that **Powered Steps** don't actually give additional walking speed, i presume because you need to wear Power Armor for it to take affect, but sheet description of the feature doesn't specify that and can confuse some people.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
