### ISSUE TITLE
Missing: Homunculus companion from Eberron: Rise of the Last War

### ISSUE THREAD

**Issue by acelegna** [aurorabuilder/elements#487]
I saw that the "Alchemist Homunculus" is available from the UA content in the Companion list, but the official Homunculus is not yet available (different stats).  Can someone please add this if a character chooses the Artificer Infusion?  

Thank you!

**Comment by swdriessen** [comment]
Yes, it's on the list of things to add after v1.0. I might include it later this week as the new version is out now.

**Comment by acelegna** [comment]
Excellent! I look forward to it  :)
