### ISSUE TITLE
Artificer Multiclass Levels Do Not Round Up

### ISSUE THREAD

**Issue by GameDevNet** [aurorabuilder/elements#488]
**Describe the issue**
Artificer MC rules state that half the Artificer levels are rounded up before being added to your MC spellcaster level total (ERLW, p.54).

However, the artificer is backed by `ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_HALF`. Causing artificer multiclass levels to be rounded down, like any other half-caster.

Sadly, this is an issue that cannot be addressed by content alone, and will require a minor code change.

**Additional context**
Here is my recommendation (For whatever it is worth 🙂) .

Inside the multiclassing related internal xml, add:
```
<element name="Multiclass Spellcasting Slots Half Round Up" type="Grants" source="Internal" id="ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_HALF_ROUNDUP">
    <rules>
        <stat name="multiclass:spellcasting:level" value="1" level="1" />
        <stat name="multiclass:spellcasting:level" value="1" level="3" />
        <stat name="multiclass:spellcasting:level" value="1" level="5" />
        <stat name="multiclass:spellcasting:level" value="1" level="7" />
        <stat name="multiclass:spellcasting:level" value="1" level="9" />
        <stat name="multiclass:spellcasting:level" value="1" level="11" />
        <stat name="multiclass:spellcasting:level" value="1" level="13" />
        <stat name="multiclass:spellcasting:level" value="1" level="15" />
        <stat name="multiclass:spellcasting:level" value="1" level="17" />
        <stat name="multiclass:spellcasting:level" value="1" level="19" />
    </rules>
</element>
```

Inside class-artificer.xml, change:
`ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_HALF` to `ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_HALF_ROUNDUP`

These two fixes can be introduced through the custom XML files (even the one that should be handled internally). However, then no two-spellcaster Artificer MC will be registered as having MC spell slots since  `ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_HALF_ROUNDUP` is not accounted for in code.

**Comment by swdriessen** [comment]
Yep, it's on my list of things to implement.
There are some internal checks for these elements which makes it a requirement because it specifically looks for certain IDs.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
