### ISSUE TITLE
Question regarding changing default Hit Dice of a class?

### ISSUE THREAD

**Issue by rjbprime** [aurorabuilder/elements#491]
My question is, I've house ruled for my campaign that Paladins have d12 Hit Dice. How do I create an XML file that modifies the Paladin class with these changes, without rewriting the whole class XML file?

**Comment by swdriessen** [comment]
Changing the _hd_ of a class is currently not supported. I had this on my todo list but it got pushed back and didn't make it in v1.0.

You don't need to re-write the whole xml file to make a class variant, just the things you change. So you could copy the paladin file and remove everything but the class element, change the source name, IDs, and hd setter (and hd in the description). (

When you don't want to go this route you could an alternative such as this: https://github.com/aurorabuilder/elements/issues/443#issuecomment-569969195 or manually adjust the sheet before printing
