### ISSUE TITLE
Dark Arts Player's Companion

### ISSUE THREAD

**Issue by rdmslight** [aurorabuilder/elements#493]
Post Link on Reddit: https://www.reddit.com/r/UnearthedArcana/comments/c1otzd/dark_arts_players_companion_v30_53_pages_of_races/

PDF: https://drive.google.com/file/d/1Kr3ZKYy3Me0ZFOhOQAmKBZlB9JUauhW5/view

**Comment by swdriessen** [comment]
You can find it here: https://github.com/community-elements/elements-reddit/pull/24

---

You can create requests for Reddit in the appropriate repository instead.

https://github.com/community-elements/elements-reddit

Learn More: https://aurorabuilder.com/posts/891/community-driven-content-reddit/
