### ISSUE TITLE
Errata Missing

### ISSUE THREAD

**Issue by Anubusss** [aurorabuilder/elements#494]
**Describe the issue**
Hello, I've noticed that at least the player's handbook has outdated information, i.e. doesn't include current errata from WOTC. 

**Additional context**
All WOTC errata is currently collected in the SA compendium:

https://media.wizards.com/2019/dnd/downloads/SA-Compendium.pdf

**Comment by swdriessen** [comment]
I will go over it all once the 2020 errata is released, which should be soon.

**Comment by swdriessen** [comment]
I've updated the content with the PHB/DMG/XGTE 2020 errata.

https://media.wizards.com/2020/dnd/downloads/SA-Compendium.pdf
