### ISSUE TITLE
Pale Master from Grimlores Grimoire

### ISSUE THREAD

**Issue by takarow** [aurorabuilder/elements#501]
Requesting the Pale Master class to be added from Grimlores Grimoire 
it looked like alot of spells for it have been there for example here 
DMSG_GRIM_Pale_Master
<element name="Bloodlink" type="Spell" source="Grimlore’s Grimoire" id="ID_DMSG_GRGR_SPELL_BLOODLINK">
		<supports>Cleric, DMSG_GRIM_Pale_Master, Sorcerer, Warlock</supports>

so wanted to request a class for it.

https://www.5esrd.com/classes/3rd-party-publisher-classes/grimlore-entertainment/the-pale-master/

**Comment by swdriessen** [comment]
Link to the 2019 version
https://www.dmsguild.com/product/244077/The-Pale-Master--DD-5e-Class

**Comment by NickVendel** [comment]
working on this
