### ISSUE TITLE
Error loading sources since last update

### ISSUE THREAD

**Issue by outisisnobody** [aurorabuilder/elements#503]
**Describe the issue**
Since updating , there has been trouble with loading sources, and the images seem not to be loading wither. I`m not really sure why it is happening. I have tried uninstalling, re-installing, doing the repair option for reinstalling, and complete re install, and manually making sure the files were in the right folder. But so far no fix would stick. 
**Additional context**
I`ll add some pictures. 
![キャプチャ](https://user-images.githubusercontent.com/63490275/79037145-7fdd9780-7c09-11ea-9d10-e4618c706a3b.PNG)
![キャプチャ2](https://user-images.githubusercontent.com/63490275/79037146-80762e00-7c09-11ea-85bc-486a1194e81c.PNG)

**Comment by swdriessen** [comment]
Please provide translations for the error messages in the first image.

What is the language/region of your OS? To narrow it down, could you try changing the region/language of windows to English and see if that resolves the issue?

**Comment by outisisnobody** [comment]
The first one the Japanese at the end says that access was refused．(for the oathbreaker file )
The second image says roughly that loading was taking too long so it gave up. 
The language and region is Japanese and Japan. I`ll see if that works, but it worked fine with the Japanese before.  But you would know better than me on this. 
I`ll update soon as I can.

**Comment by outisisnobody** [comment]
I change the language to English but it still coming up with the same error message, but this time I screenshot it in English (sorry, about having it in Japanese, I completely spaced on that. )


![Capture](https://user-images.githubusercontent.com/63490275/79063951-fa78e680-7cdf-11ea-97f5-c01cdb3067f6.PNG)
![Capture2](https://user-images.githubusercontent.com/63490275/79063954-fbaa1380-7cdf-11ea-95d4-6e131860e01d.PNG)
![Capture3](https://user-images.githubusercontent.com/63490275/79063955-fc42aa00-7cdf-11ea-955c-2923717badfc.PNG)
![Capture4](https://user-images.githubusercontent.com/63490275/79063957-fc42aa00-7cdf-11ea-88ff-0fe024b430ae.PNG)
![Capture5](https://user-images.githubusercontent.com/63490275/79063958-fcdb4080-7cdf-11ea-92f2-ecd94c0df9e3.PNG)

**Comment by swdriessen** [comment]
Something is blocking access to the `5e character builder` folder in your documents, maybe antivir or something like that. You can allow Aurora access or try running it as administrator.

The error where it says it timed out is one you might get when checking for updates and the connection wasn't able to connect after 30 seconds. Might be caused by bad connection or some server downtime. You can turn off auto-updates for content in the settings if it happens often.

**Comment by outisisnobody** [comment]
Ok i will try that! Thank you!

**Comment by outisisnobody** [comment]
It was 120% the antivirus software`s fault! Thank you!
