### ISSUE TITLE
Content Request - Slayer (Class)

### ISSUE THREAD

**Issue by omerbl1996** [aurorabuilder/elements#504]
I have seen those in DMS Guild and those seemed awesome. Think many people here will appreciate the content.

_documents removed_

https://www.dmsguild.com/product/276205/The-Slayer-Class
addition: Fiendhunter subclass

**Comment by swdriessen** [comment]
please make one request / source and do not post documents

**Comment by omerbl1996** [comment]
So if I'll make it to be 2 separate requests its ok? And how will you pit
the classes into the aurora without the files? The content I brought costs
money. Can I send in the files but from a google drive source or something
like that?

בתאריך יום א׳, 12 באפר׳ 2020, 18:27, מאת Bas Driessen ‏<
notifications@github.com>:

**Comment by Azzzzzy** [comment]
You could always ask around in the [Community Discord](https://discord.gg/MmWvNFV) and there is a simple beginner tutorial in there too if you want to try making it yourself.

**Comment by swdriessen** [comment]
Yes, separate is good.

If I don't have it or I don't know someone who has it, I will request it from you. Depending on the price and content sometimes it will just buy it myself. Just don't post direct links to payed content. Documents are also marked and can be linked to your account, and you run the risk of having your DMs Guild account revoked/banned.

**Comment by omerbl1996** [comment]
https://app.luminpdf.com/viewer/5e933a7ff6801600186d8378
https://app.luminpdf.com/viewer/5e933a575fbc3400172796d3

I hope these links will suffice.

**Comment by swdriessen** [comment]
**> Just don't post direct links to payed content.**

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
