### ISSUE TITLE
The Blackstaff's Warlock Codex

### ISSUE THREAD

**Issue by omerbl1996** [aurorabuilder/elements#506]
Here are the files for the Warlock codex. It has many awesome things that many players will like! Hope this time the way I posted this is ok :)

https://www.dmsguild.com/product/308482/The-Blackstaffs-Warlock-Codex

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
