### ISSUE TITLE
Attack and Spellcasting Section

### ISSUE THREAD

**Issue by Julitutu** [aurorabuilder/elements#509]
Is there an option or possibility of expanding the number of slots in the "Attack and spellcasting" section to more than 4? My fighter has a lot of weapons and I'd like to see all of them in that section!
You are doing an Awsome work!
Congratulation!

**Comment by swdriessen** [comment]
You can not.
Like the official character sheet, it's a sheet I made with fillable area's and the character builder fills it in.

You can fill the area below it with custom text from the attacks and spellcasting tab in the UI.
