### ISSUE TITLE
Blood Hunter 2020 (Order of the Lycan) issues

### ISSUE THREAD

**Issue by acelegna** [aurorabuilder/elements#515]
Hey! I love playing this class and wonderful job implementing all the SEVERAL features this class has. I have come across 2 issues though (so far, only for the Order of the Lycan subclass):

1) **Hybrid Transformation**: Once you receive this option, Aurora generates:
_"You can transform into your hybrid form indefinitely."_ 
When in actuality, the official PDF says:
_"Up to 1 hour.  Once you use this feature, you must finish a short or long rest before you can use it again"_
At level 11th, you can use it twice, but still 1 hour long each time.  It's not until level 18th when it become "indefinitely"

2) The Bloodlust's DC always stays at 8 instead of 8 + (BH level / 3)

**Comment by swdriessen** [comment]
1) added missing level requirement for the sheet description of hybrid transformation
2) fixed description on, the stat is the correct one

**Comment by acelegna** [comment]
I saw the fix on the first issue! Thank you!

As far as the 2nd, I beg to differ that the stat is incorrect (see image).  Just to test it out, I created a test PC BH (Lycan) 12 level.  The Bloodlust DC should be 12 at this point [8 + (12/3)) ....but still appears as 8

![Bloodlust](https://user-images.githubusercontent.com/55709902/80831188-8bd4cd80-8ba7-11ea-97e6-b3e8cc418be4.jpg)

**Comment by swdriessen** [comment]
That's the old version which was fixed in https://github.com/aurorabuilder/elements/commit/dbf8b3720d9ade189c93fdb98103509463107b4c
Just forgot to update that part of the description, try downloading the latest version of the pdf.

**Comment by acelegna** [comment]
So they did! I apologize
(You would think that when I purchased it from DM Guild, they would sent me an email or something if they updated it :P)
