### ISSUE TITLE
Paladin Aura of Protection (lvl.6) Saving Throw Bonus not Applied

### ISSUE THREAD

**Issue by mgiuntoni** [aurorabuilder/elements#516]
**Describe the issue**
When Paladin reaches level 6 gain Aura of Protection [10"] that reads:

> Aura of Protection
> Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus.
> 
> At 18th level, the range of this aura increases to 30 feet.

This bonus is **not** applied to saving trows in the character sheet. 

**Additional context**
In the code it seems present but somehow does not trigger.
Extract from `elements/core/players-handbook/classes/class-paladin.xml`

```
	<element name="Aura of Protection" type="Class Feature" source="Player’s Handbook" id="ID_WOTC_PHB_CLASS_FEATURE_PALADIN_AURA_OF_PROTECTION">
		<description>
			<p>Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus.</p>
			<p class="indent">At 18th level, the range of this aura increases to 30 feet.</p>
		</description>
		<sheet>
			<description>Whenever you or a friendly creature within {{aura of protection:range}} feet of you must make a saving throw, the creature gains a +{{aura of protection:save bonus}} bonus to the saving throw. You must be conscious to grant this bonus.</description>
		</sheet>
		<rules>
			<stat name="aura of protection:range" value="10" bonus="base" />
			<stat name="aura of protection:range" value="30" level="18" bonus="base" />
			<stat name="aura of protection:save bonus" value="1" bonus="base"/>
			<stat name="aura of protection:save bonus" value="charisma:modifier" bonus="base"/>
		</rules>
	</element>
```

**Comment by NickVendel** [comment]
Yes, it's known "issue", and i'm pretty sure it's due to the "You must be conscious to grant this bonus" condition. When feature has some kind of condition, rather than granting bonus outright, developer usually sticks to displaying bonus in the description, since it can be misleading when bonus applied to you all the time even "when you're unconscious".

**Comment by swdriessen** [comment]
Conditional statistics are not implemented yet, use the snippet below (save as xml file to `custom\user`) if you want the sheet to reflect this at all times for the ability saving throws.

```
<?xml version="1.0" encoding="utf-8" ?>
<elements>

	<append id="ID_WOTC_PHB_CLASS_FEATURE_PALADIN_AURA_OF_PROTECTION">
		<rules>
			<stat name="strength:save:misc" value="aura of protection:save bonus" />
			<stat name="dexterity:save:misc" value="aura of protection:save bonus" />
			<stat name="constitution:save:misc" value="aura of protection:save bonus" />
			<stat name="intelligence:save:misc" value="aura of protection:save bonus" />
			<stat name="wisdom:save:misc" value="aura of protection:save bonus" />
			<stat name="charisma:save:misc" value="aura of protection:save bonus" />
		</rules>
	</append>

</elements>
```

**Comment by mgiuntoni** [comment]
Thanks a lot.
