### ISSUE TITLE
Request for Farmer class

### ISSUE THREAD

**Issue by outisisnobody** [aurorabuilder/elements#517]
https://www.dandwiki.com/wiki/Farmer_(5e_Class)#Ability_Score_Increase

I would like to request this class please.

**Comment by swdriessen** [comment]
You can create requests for D&D Wiki in the appropriate repository instead.

https://github.com/community-elements/elements-dndwiki

Learn More: https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/
