### ISSUE TITLE
Race Request: Arachne (spiderfolk)

### ISSUE THREAD

**Issue by outisisnobody** [aurorabuilder/elements#518]
https://www.dndbeyond.com/races/96759-arachne

May I have this race added please?
Thank you!

**Comment by swdriessen** [comment]
This is out of the project scope, please read the Content Requests section in the guidelines.

https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md

**Comment by outisisnobody** [comment]
Oh, sorry about that.
