### ISSUE TITLE
Content Request - Grim Hollow

### ISSUE THREAD

**Issue by animegeek999** [aurorabuilder/elements#520]
_removed link to pdf, added link to website_ (see [guidelines](https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md) for requests)

https://grimhollowstore.com/products/grim-hollow-campaign-setting-pdf

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
