### ISSUE TITLE
High level character Class bug

### ISSUE THREAD

**Issue by HannaWalgrave** [aurorabuilder/elements#523]
![aurora screenshot](https://user-images.githubusercontent.com/19911863/81322440-437c4a80-9094-11ea-9570-4d6700f78e10.PNG)
![screenshot aurora](https://user-images.githubusercontent.com/19911863/81322444-44ad7780-9094-11ea-8808-877a9fddca96.PNG)

When I created a level 12 Tabaxi Rogue I could not progress to Next Selection when filling out my class options. 

Beyond level 6 the expertise window is added twice and when you select one the other pne "dissapears" as an option but when clicking next selection the option is marked as "need to fill this in" but you can't.

**Comment by swdriessen** [comment]
You can only take expertise in a skill in which you have proficiency. Once you select one of those, more options will become available. You can manually navigate to the proficiency tab to select them.

In the future the next selection will skip selections that have no options left.
