### ISSUE TITLE
adventuring gear missing and feedback

### ISSUE THREAD

**Issue by Balisticbananas** [aurorabuilder/elements#524]
-Small knife and Little bag of sand missing from the scholar's pack and the equipment list
-would be nice to have a passive investigation on the character sheet.

**Comment by NickVendel** [comment]
• There's indeed no **Small Knife** or **Bag of Sand** items in the Builder, for some reason.
• I would also like ability to add either/both Passive Investigation and Passive Insight on Character Sheet, but i think that wouldn't happen soon, since i think that would require customizable sheet.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
