### ISSUE TITLE
error handling, what FILE ?

### ISSUE THREAD

**Issue by Fenaldar** [aurorabuilder/elements#526]
Hello,
I started to translate a lot of stuff in German, and sometimes I get an error Message like this:

**SYSTEM.XML.XMLEXCEPTION**
illegal char line 78, position 303

This ist good, BUT in what **FILE** is the error?

**Comment by swdriessen** [comment]
If the issue is in the file it should show the filename when loading the content. 

At what point does the error appear? I assume the issue appears when selecting a feature or item and the issue is with a generated description.
If you can reproduce the issue I can take a look at it and include the element name/id in the exception message.

**Comment by Fenaldar** [comment]
> If the issue is in the file it should show the filename when loading the content.

This works if the XML file already exists when Aurora is started.

> At what point does the error appear? I assume the issue appears when selecting a feature or item and the issue is with a generated description.
> If you can reproduce the issue I can take a look at it and include the element name/id in the exception message.

However, the file name was not displayed while the content files were being updated.

![Capture](https://user-images.githubusercontent.com/49685258/81896972-e4e42e80-95b5-11ea-9c45-fc234c7fdc84.JPG)

**Comment by swdriessen** [comment]
Be sure to test loading the files locally in Aurora before pushing the changes to GitHub. You will get this message also when you load your local files (during the splash screen) and then you will also see the name of the file.

In the future I'll also include the url of the file when one of these exceptions occurs, but files should be tested locally before publishing.
