### ISSUE TITLE
Typographical Error

### ISSUE THREAD

**Issue by WouterSchmahl** [aurorabuilder/elements#527]
**Issue:**
Under the Far Traveler description, in the subcategory 'where are you from?', an optional choice for the background, there is a small typographical error in the homeland 'Kara-Tur'. The first line reads Faen1n rather than Faerûn.

![image](https://user-images.githubusercontent.com/65302444/81839487-e37c1d00-9547-11ea-83d8-fc7e4684ca6a.png)

**Comment by swdriessen** [comment]
It's fixed, thanks.
