### ISSUE TITLE
Artificer Steel Defender "Might of the Master" Not Applying Proficiency Bonus Increases

### ISSUE THREAD

**Issue by erjicles** [aurorabuilder/elements#529]
When my artificer (battle smith subclass) levels up and gains a proficiency bonus increase, the character sheet is not applying the corresponding "might of the master" stats increases for his steel defender. The steel defender's stats are all shown at their original levels except HP.

**Comment by swdriessen** [comment]
Yes, the sheet descriptions for the companion are currently static. You'll have to keep track of it yourself for now.
