### ISSUE TITLE
Additional official 5Ed Sets as Adventures in the Middle Earth

### ISSUE THREAD

**Issue by Julitutu** [aurorabuilder/elements#530]
Hi!
I was wondering if at any point in the project you were thinking of adding Adventures in the Middle Earth character creation and content as they are official Wizard of the Coast 5 Ed. 
Since I'm not a programmer, I don't know how I could help. But I am willing to help in whatever way I can to keep this great project moving forward!
![516zEc0dU+L _SX258_BO1,204,203,200_](https://user-images.githubusercontent.com/58534179/82588534-55b8b700-9b71-11ea-9e35-e347e8a107b9.jpg)

**Comment by swdriessen** [comment]
This is out of the project scope, please read the Content Requests section in the guidelines.

https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md
