### ISSUE TITLE
Death Domain: Missing Spells

### ISSUE THREAD

**Issue by else-where** [aurorabuilder/elements#532]
This subclass should have the ability to learn one necromancy cantrip from any class but only cleric class necromancy cantrips show up from core and other sources to learn.

**Comment by swdriessen** [comment]
Be sure to select the correct selection option; 'Necromancy Cantrip'. This does allow for a selection from other classes (this doesn't mean there are a lot).
For example the 'Sapping Sting' (EGTW) is non-cleric and shows up for a selection
