### ISSUE TITLE
Concentration filter

### ISSUE THREAD

**Issue by krashenbern** [aurorabuilder/elements#535]
Is there any way to have the concentration button filter spells that require concentration from spells that don't? 

I guess what I mean is, on the spellcasting tab - It shows all available spells. 
If I click the concentration button, it will show only the spells that require concentration. 
I would like to be able to click it again and show only the spells that DON'T require concentration. 
... maybe splitting the button into two would be less confusing? 

Thank you!

**Comment by swdriessen** [comment]
The current version is as good as closed for any new features or changes. If i ever release another version in the future things like these will be taken into account.
