### ISSUE TITLE
Wizard, adding spells you find in your journey

### ISSUE THREAD

**Issue by wizzle1989** [aurorabuilder/elements#54]
I don't see a way to add spells to my sheet if I find a spell book and copy them into my spell book as a wizard. Also, spell duplication for example as a necromancer I get animate dead at level 6 if I don't already have it but I took it at level 5 so once I leveled up I ended up with duplicate animate dead spells. I just turned one off in the view and it was fine but that might be causing other issues.

**Comment by swdriessen** [comment]
Adding extra spells is not yet implemented.

**Comment by alorg** [comment]
Hi resurrecting the above request, mainly to show interest in this function. Apart from that extremely happy with the product, keep it up, please.

**Comment by swdriessen** [comment]
You can add additional spells based on spellcaster from the new equipment categories 
https://aurorabuilder.com/posts/977/preview-version-1191216/
