### ISSUE TITLE
Content Request - Death Knight

### ISSUE THREAD

**Issue by TheOSC** [aurorabuilder/elements#546]
**[Source URL](https://www.gmbinder.com/share/-LoettmZ3jFXcBgVFVwF)**
A link to the website where the requested content is publicly available.

This is a custom class made by me. It has a few unorthodox mechanics however that make it a bit out of my scope to code in XML for Aurora, namely the Rune and Runic Power systems.

**Comment by swdriessen** [comment]
There is a homebrew-support channel on the discord if you need help implementing a certain feature. This repository is not for support.

https://discord.gg/MmWvNFV
