### ISSUE TITLE
Languages from Sword Coast Adventurer’s Guide Missing

### ISSUE THREAD

**Issue by falconflicker** [aurorabuilder/elements#549]
The optional human languages from the Sword Coast Adventurer’s Guide are missing.

I have recommended code to use here.
`<?xml version="1.0" encoding="utf-8" ?>
<elements>
	<info>
		<update version="0.0.1">
			<file name="languages.xml" url="https://raw.githubusercontent.com/aurorabuilder/elements/master/supplements/eberron-rising-from-the-last-war/languages.xml" />
		</update>
	</info>
	<element name="Alzhedo" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_ALZHEDO">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Calishite.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Chessentan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_CHESSENTAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Mulan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Chondathan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_CHONDATHAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Chondathan and Tethyrian.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Damaran" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_DAMARAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Damaran and Nar. (written in Dethek)</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Dambrathan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_DAMBRATHAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Arkaiun. (written in Espruar)</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Guran" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_GURAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Gur. (a patois of Roushoum and Rashemi)</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Halruaan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_HALRUAAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Halruaan. (written in Draconic)</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="llluskan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_ILLUSKAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the llluskan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Midani" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_MIDANI">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Bedine.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Mulhorandi" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_MULHORANDI">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Mulan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Rashemi" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_RASHEMI">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Rashemi.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Roushoum" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_ROUSHOUM">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the lmaskari.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Shaaran" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_SHAARAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Shaaran. (written in Dethek)</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Shou" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_SHOU">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Shou.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Thayan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_THAYAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Mulan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Tuigan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_TUIGAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Tuigan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Turmic" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_TURMIC">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Turami.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Uluik" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_ULUIK">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Ulutiun.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Untheric" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_UNTHERIC">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Mulan.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
	<element name="Waelan" type="Language" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_LANGUAGE_WAELAN">
		<supports>Starting,Standard</supports>
		<description>
			<p>Mainly spoken by the Ffolk.</p>
		</description>
		<setters>
			<set name="standard">true</set>
		</setters>
	</element>
</elements>`

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
