### ISSUE TITLE
Blood Hunter not up to date

### ISSUE THREAD

**Issue by Ivalice1215** [aurorabuilder/elements#553]
The Blood Hunter has been revised to no longer use Wisdom, now using Intelligence for Blood Rites and other abilities. It's Saving throw abilities are now Dex and Int.
https://www.dmsguild.com/product/301641/Blood-Hunter-Class-for-DD-5e-2020

**Comment by swdriessen** [comment]
https://aurorabuilder.com/posts/1092/additional-content-blood-hunter-2020/
