### ISSUE TITLE
Request: Legends of Runeterra: Bilgewater Content

### ISSUE THREAD

**Issue by Petersonian** [aurorabuilder/elements#554]
https://www.dndbeyond.com/sources/lrdtob

This material is going to be pulled down at some point. Seems the agreement between Riot and Wizards didn't hold or something. I'd love for it to be available on Aurora and archived that way, too.

**Comment by swdriessen** [comment]
It's _on hold_ here: https://github.com/aurorabuilder/elements/pull/545 due to _out of scope_ awaiting if it might get put on DMsGuild (writer of this content also has content on DMsGuild). You can still take the files from there and archive it yourself for personal use.
