### ISSUE TITLE
Sorting via integer value & rarity

### ISSUE THREAD

**Issue by RyanPallesen** [aurorabuilder/elements#555]
**Additional context**
Currently equipment is sorted by alphabetical regardless of the table you are sorting by. E.G. sorting by 'price' puts 15 and 15000 gp next to eacher, when it would make more sense to go by integer value. This can be extended to weight and rarity, where rarity should be in rarity level and weight by integer.

**Comment by swdriessen** [comment]
The application is closed for new features and updates so no changes in that regard currently but this has been on my list.
