### ISSUE TITLE
Mage Armor and item cards for spell scrolls 

### ISSUE THREAD

**Issue by ImelchorI** [aurorabuilder/elements#558]
im very much enjoying this character builder so far.

id like to make two requests in regard to some of the functionalities.

first, id like to ask if its possible to add Mage Armor (as the wizard spell) as its own armor type to the armor tab in the equipment, or somehow allow mage armor to be equipped and displayed on the character sheet that way.

My eldritch knight is using this spell as his armor of choice, and it would generally be useful to have this as a default "equipped armor" for wizards who are using the spell aswell.

another problem ive noticed, is that displaying spell scrolls as an item card on your character sheet doesnt contain the spells description, but the general rule of the use of spell scrolls.

imo it would be more useful to have the description of the specific spell displayed on the spell scrolls item card instead.

thank you for your time and efford to make such an amazing tool.

**Comment by swdriessen** [comment]
Thanks, the application is closed for new features and updates so no changes in that regard.

In regards to mage armor, i've always just created a proxy item that gives the desired effect. I've attached a file which adds it to your equipment section so you can add and equip it. It will give you the appropriate bonus to AC and your sheet will reflect this.
[mage armor.zip](https://github.com/aurorabuilder/elements/files/5010420/proxy-effects.zip)

As for the spell scroll, what you could do is add the same spell from 'Equipment>Additional Spells' to have it show up as a spell card and remove it after you've used the scroll.

**Comment by ImelchorI** [comment]
aw man, its not developed anymore? thats a shame, because this seems to be the best application out there.

i already figured out the same workaround :)

the only problem i see with this is, that in some instances like bracers of defense, its counted as wearing armor, which causes the bracers to be ineffective, even though the values should stack.

there might be other similar unwanted side effects.

does youre version fix that?

maybe instead of an armor piece i should make a cloak instead, since the game rules technically allow wearing multiple magic cloaks at the same time, layered on top of each other, it shouldnt cause conflicts.

**Comment by swdriessen** [comment]
info on the project state [here](https://aurorabuilder.com/posts/1298/important-project-update-survey/)

and yes, that file i attached works with bracers of defense since it's just an applied effect
