### ISSUE TITLE
Monk Monastic Tradition: Way of Tranquility

### ISSUE THREAD

**Issue by Kagukara** [aurorabuilder/elements#56]
Is there anyone able add this monastic tradition to aurora builder, I have had a go at the code, but I am not too sure if it is right.
[https://media.wizards.com/2016/dnd/downloads/M_2016_UAMonk1_12_12WKWT.pdf](url)

Here is the code I came up with:
`	<?xml version="1.=" encoding="UTF-8"?>
	<elements>
		<info>
			<name>Way of Tranquility</name>
			<description>The Way of Tranquility Monastic Tradition from the Unearthed Arcana.</description>
			<author url="">Wizards of the Coast</author>
			<update version="0.0.1">	
				<file url="" name="monk_wayoftranquility.xml"/>
			</update>
		</info>
			
		<element name="Way of Tranquility" id="ID_WOTC_UA_ARCHETYPE_MONK_WAY_OF_TRANQUILITY" source="Unearthed Arcana" type="Archetype">
			<supports>Monastic Tradition</supports>
			<description>
				<p>Monks of the	Way of Tranquility see violence as a last resort. They use diplomacy, mercy, and understanding to resolve conflicts. If pushed, though,	they are capable warriors who can bring	an end to the unjust or	cruel folk who refuse to listen	to reason. When	adventuring, these monks make excellent	diplomats. They	are also skilled in the	healing	arts, and can preserve their allies in the face	of daunting foes.</p>
				<div element="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_PATH_OF_TRANQUILITY"/>
				<div element="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_HEALING_HANDS"/>
				<div element="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_EMISSARY_OF_PEACE"/>
				<div element="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_DOUSE_THE_FLAMES_OF_WAR"/>
				<div element="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_ANGER_OF_A_GENTLE_SOUL"/>
			</description>
			<rules>
				<grant name="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_PATH_OF_TRANQUILITY" type="Archetype Feature" level="3"/>
				<grant name="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_HEALING_HANDS" type="Archetype Feature" level="3"/>
				<grant name="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_EMISSARY_OF_PEACE" type="Archetype Feature" level="6"/>
				<grant name="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_DOUSE_THE_FLAMES_OF_WAR" type="Archetype Feature" level="11"/>
				<grant name="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_ANGER_OF_A_GENTLE_SOUL" type="Archetype Feature" level="17"/>
			</rules>
		</element>
		<element name="Path of Tranquility" id="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_PATH_OF_TRANQUILITY" source="Unearthed Arcana" type="Archetype Feature">
		<element name="Path of Tranquility" id="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_HEALING_HANDS" source="Unearthed Arcana" type="Archetype Feature">
		<element name="Path of Tranquility" id="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_EMISSARY_OF_PEACE" source="Unearthed Arcana" type="Archetype Feature">
		<element name="Path of Tranquility" id="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_DOUSE_THE_FLAMES_OF_WAR" source="Unearthed Arcana" type="Archetype Feature">
		<element name="Path of Tranquility" id="ID_WOTC_UA_ARCHETYPE_FEATURE_WAY_OF_TRANQUILITY_ANGER_OF_A_GENTLE_SOUL" source="Unearthed Arcana" type="Archetype Feature">`

**Comment by swdriessen** [comment]
It has been added in #58

(Your email in the contact form was incorrect and I was unable to reply.)

**Comment by Kagukara** [comment]
oh
