### ISSUE TITLE
DMSG: Exploring Eberron

### ISSUE THREAD

**Issue by Azzzzzy** [aurorabuilder/elements#565]
**https://www.dmsguild.com/product/315887/Exploring-Eberron**
A link to the website where the requested content is publicly available.

Backgrounds:
- [x] Changeling Traveler
- [x] Dhakaani Goblin
- [x] Malenti

Races:
- [x] Aasimar Subraces
- [x] Aereni Elf
- [ ] Ruinbound Dwarf
- [ ] Dhakaani Hobgoblin
- [ ] Dhakaani Goblin
- [ ] Dhakaani Bugbear
- [x] Gnoll

- [x] Racial Feats (Done by Konard)

Class Options:
- [x] Artificer: Forge Adept (Done by Konard)
- [x] Artificer: Maverick (Done by Konard)
- [ ] Artificer Infusions
- [ ] Bard: College of Dirge Singer
- [x] Cleric: The Mind Domain
- [x] Druid: Circle of the Forged (Done by Canis Rex)
- [ ] Monk: Way of the Living Weapon

Magic Items
- [ ] Common Magic Items
- [ ] Dhakaani Magic Items
- [ ] Dragonmark Focused Items
- [ ] Siberys Dragonmarks
- [ ] Misc Magic Items
- [ ] Symbionts

**Comment by ngrinschgl** [comment]
Oh this would be sweet.

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.
