### ISSUE TITLE
Gargoyle Race request

### ISSUE THREAD

**Issue by Mettatex** [aurorabuilder/elements#577]
https://www.dandwiki.com/wiki/Gargoyle_(5e_Race)
A link to the website where the requested content is publicly available.
I have no idea if what Im doing is correct or not, sorry.

**Comment by swdriessen** [comment]
You can create requests for D&D Wiki in the appropriate repository instead.

https://github.com/community-elements/elements-dndwiki

Learn More: https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/

**Comment by Mettatex** [comment]
My bad! I did just what you said, excuses!
