### ISSUE TITLE
Ability to increase font size

### ISSUE THREAD

**Issue by nemikan** [aurorabuilder/elements#578]
Request: Allow modifying the application's font size via the application settings.

Issue Details:
I'm using a 35 inch ultra wide screen monitor on a resolution of 3440×1440 and the font is incredibly small to the point of being unreadable without using a magnifier. Attached my default web browser font size in comparison to the Aurora App. I've tried modifying Window's window size settings (https://superuser.com/questions/1069620/enlarge-a-specific-application-in-windows-10) and Aurora ignores them. 

![image](https://user-images.githubusercontent.com/71042237/93716371-11e0b900-fb35-11ea-9eaf-107ebf8c8929.png)

**Comment by Memnarch1113** [comment]
This has been the most-requested feature from people in my campaign!

**Comment by swdriessen** [comment]
The application is closed for new features and updates so no changes in that regard. More information about the project status in the news articles on the website.
