### ISSUE TITLE
Boons, Blessings and Charms addition option

### ISSUE THREAD

**Issue by JasperNakamura** [aurorabuilder/elements#65]
Would there be in the future add the options above to characters as some may be rewarded these from their DM or play a campaign that exceeds level 20

**Comment by swdriessen** [comment]
I was thinking about the boons when implementing the equipment section but i held off for the moment since they are not really equipment yet can be treated as such.

They will be included at some point, I just haven't decided yet how to implement them.

**Comment by swdriessen** [comment]
Added in #395
