### ISSUE TITLE
Custom health

### ISSUE THREAD

**Issue by gurulej99** [aurorabuilder/elements#69]
I just updated the program and can't seem to put in a custom health option other than editing the health after creating the character sheet, despite deselecting the average health option. Am I overlooking something?

**Comment by swdriessen** [comment]
In the **level up panel** you can slide the hit die for each level depending on the class.

**Comment by gurulej99** [comment]
Ah, ok. I think my problem stemmed from the fact that I started at 5th level. I didn't use the level up panel. I'll see if I can go back in and fix the health tonight

**Comment by gurulej99** [comment]
Yep that worked. Thanks!
