### ISSUE TITLE
Trait, Ideal, Bond, Flaw default text persists to override on reselect.

### ISSUE THREAD

**Issue by solo64** [aurorabuilder/elements#7]
When the player selects new background information -- traits, ideal, bond, flaw -- and those backstory fields are populated, the previous selections' text becomes the override of the new selections' text. That is, the default text of previous selections is not replaced with the default text of new selections because the previous selections are directly written into their backstory fields and treated as overrides afterwards. The result is that when the player decides to change their background info and updates their sheet using new selections, it doesn't make any changes to the sheet or the backstory fields because the previous selections' text is persisting in their backstory fields and overriding the new selections' text as a consequence.

Note: I make the assumption that this behavior is intended if a player wants to customize their background information beyond the scope of selection items, but unintended if the player chooses to use default values instead. The following list reveals the steps I took to reproduce this issue.

1. Create a new character.
2. Confirm state of relevant entries under "Manage->Backstory".\*
3. Select a background.
4. Select traits, ideal, bond, flaw.
5. Select a race.\**
6. Repeat step 2.\***
7. Confirm state of relevant entries in character sheet preview under "Character Sheet->Character Sheet".\****
8. Update character sheet preview.
9. Repeat step 7.\*****
10. Repeat steps 2, 4, 6-9 in that order.\\*

\* the entries should appear empty at this point.
\** for some reason, the entries will not fill if something else isn't selected.
\*** the entries should appear filled at this point.
\**** there shouldn't be anything filled for background-relevant fields on the sheet at this point.
\***** the background-relevant fields on the sheet should populate now.
\\* this is the cycle when a player might tweak their background info, but you should notice that the background-relevant fields will not change despite that they do on the first round.

**Comment by swdriessen** [comment]
** this is most likely due to the selection being a 'cosmetic' list instead of actual elements. Will check to add triggers to pupulate some fields after list selections have changed. The player will only notice after saving and loading again when the checkmark appears.

I noticed this too when dragging and dropping ability scores around, it doesn't reflect the change so i forgot to recalculate after that too.

Will check to fix it for the next version.
