### ISSUE TITLE
Curse of Strahd Backgrounds Gaming Set Issue

### ISSUE THREAD

**Issue by TrikkiNikki** [aurorabuilder/elements#76]
It's ya gurl, back again with some Random Bullshit(TM), because I normally mess around with this program when I'm bored.

It looks like the Curse of Strahd backgrounds that give you a gaming set proficiency, iron route bandit and Stojanow Prisoner, don't actually allow you to choose from anything, like the is no list.

I looked through the code, because I know the slightest mess-up breaks everything, and saw the code for these two.

<select type="Proficiency" name="Gaming Set (Iron Route Bandit)" supports="Gaming set"/>
<select type="Proficiency" name="Gaming Set (Stojanow Prisoner)" supports="Gaming set"/>

Then I looked at the Soldier background code, which works.

<select type="Proficiency" name="Gaming Set" supports="Gaming Set" />

It seems like on the "supports="Gaming Set" />", it is capitalized for the Soldier, but not for the other two. Don't know if this happens for any of the others, but whenever you get around to it, that would be cool. Thanks.

**Comment by swdriessen** [comment]
Thanks, i'll take a look at them to fix these issues.
