### ISSUE TITLE
Character Collection Screen Organization

### ISSUE THREAD

**Issue by JasperNakamura** [aurorabuilder/elements#78]
I use this application a lot and make a large number of characters. Thus, implementing something like in application folders or some other sort of design that can help sort out characters from different campaigns or other reasons easily would be helpful.

**Comment by swdriessen** [comment]
I'll make a note of this to allow for some kind of grouping in the future.

Currently you can mark a character as favorite when you save them. This will make them show up first in the collection and mark them with a gold color.
