### ISSUE TITLE
Character Sheet PDF Font Change

### ISSUE THREAD

**Issue by SeeFue** [aurorabuilder/elements#83]
Can we change the font on the character sheet?  Particularly the Attacks and Spellcasting section.  The font is too large to fit all of the text in the fillable sections.

**Comment by swdriessen** [comment]
The official sheets have this limitation. Next version will have custom character sheets with more space for names of weapons.

**Comment by Julitutu** [comment]
I know this requeste it's closed but I don't know where to ask, Is there an option to expand the number of slots in the "Attack and spellcasting" section to more than 4?
