### ISSUE TITLE
The Shaman Class 

### ISSUE THREAD

**Issue by JMcCham89** [aurorabuilder/elements#89]
I would love if this class could make it in. I can send the files to those who need them. I think it would be great if this class could be used by more people.

**Comment by swdriessen** [comment]
Sounds good!

You could create a pull request to have it added (i'm starting to work on the backlog again a bit after having been too busy).

You could also post it in the [subreddit](https://www.reddit.com/r/aurorabuilder) with a link to the file / source so people can test it, thank you for it, and provide feedback there.

**Comment by swdriessen** [comment]
Basicly: create a fork, create a branch, make changes, commit changes, create pull request.

I'd recommend watching some video's on youtube on the workflow of github. You can make repositories on your account, play around, test things as much as you want.

Meanwhile you can post it on the subreddit if you want to get some feedback already.
