### ISSUE TITLE
Bug - Druidic Language Available to non-Druids

### ISSUE THREAD

**Issue by InsanityAtHeart** [aurorabuilder/elements#93]
Hey there, I noticed that when choosing bonus language proficiencies that a PC might know, the Druidic language is available to be chosen by anyone, no matter the class. This language is only allowed for those who have the Druid class so is there a way that language could be restricted to Druids on the builder in order to avoid confusion?

**Comment by swdriessen** [comment]
closed until further notice, enhancement for future
