### ISSUE TITLE
Shadow Sorceror not learning Darkness spell

### ISSUE THREAD

**Issue by Linerunner99** [aurorabuilder/elements#97]
Shadow Sorcerors automatically learn the Darkness spell upon reaching 3rd level in the class but the Builder is not giving it to them.

**Comment by swdriessen** [comment]
This was closed with the fix linked in the close message:

> swdriessen closed this in b5599f2 2 days ago

When you click the link you'll be taken to the commit where i've added the spell to the feature.

**Comment by Linerunner99** [comment]
Ahh ok, wasn't aware of those links until now. Sorry for the confusion.
