### ISSUE TITLE
Content Request - Unearthed Arcana - Stone Sorcerous Origins

### ISSUE THREAD

**Issue by Mathitos** [aurorabuilder/elements#99]
I'm willing to help doing this, just dont know how to create a xml that the aurora would accept

**Comment by swdriessen** [comment]
Thanks, but coincidentally this was added last week. 
You can see how the XML looks like here if you want to try and create some content yourself: https://github.com/aurorabuilder/elements/blob/df5a715bb51527d92eb97d3cd01444f62a132ced/unearthed-arcana/2017/20170206.xml#L225-L226

**Comment by Mathitos** [comment]
@swdriessen I tried to make a xml( https://gist.github.com/Mathitos/2c1962994a4eec029989f9ef2ea42ef1) but aurora don't accept it, do have any template I can use to validate my xml?

**Comment by swdriessen** [comment]
This background works fine for me. Did you place it in the **docs/5e builder/custom** folder?

**Comment by Mathitos** [comment]
Actually I tried by fetching my gist url

**Comment by swdriessen** [comment]
Fetching is currently only for the index files, so it's saved as background-hellborn.index and when loading it's looking in .xml files for content.

See example for index file: https://github.com/aurorabuilder/elements/blob/master/third-party/dnd-wiki.index

The index file has links to .xml content files which the builder will download so only the url for the index file has to be shared to get all content.
